(function() {
var _UDS_CONST_LOCALE = 'vi';
var _UDS_CONST_SHORT_DATE_PATTERN = 'DMY'; 
var _UDS_MSG_SEARCHER_IMAGE = ('H\u00ecnh \u1ea3nh'); 
var _UDS_MSG_SEARCHER_WEB = ('Web'); 
var _UDS_MSG_SEARCHER_BLOG = ('Blog'); 
var _UDS_MSG_SEARCHER_VIDEO = ('Phim \u1ea3nh'); 
var _UDS_MSG_SEARCHER_LOCAL = ('B\u1ea3n \u0111\u1ed3'); 
var _UDS_MSG_SEARCHCONTROL_SAVE = ('l\u01b0u'); 
var _UDS_MSG_SEARCHCONTROL_KEEP = ('gi\u1eef'); 
var _UDS_MSG_SEARCHCONTROL_INCLUDE = ('bao g\u1ed3m'); 
var _UDS_MSG_SEARCHCONTROL_COPY = ('copy'); 
var _UDS_MSG_SEARCHCONTROL_CLOSE = ('\u0111\u00f3ng'); 
var _UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS = ('Li\u00ean k\u1ebft nh\u00e0 t\u00e0i tr\u1ee3'); 
var _UDS_MSG_SEARCHCONTROL_SEE_MORE = ('xem th\u00eam k\u1ebft qu\u1ea3...'); 
var _UDS_MSG_SEARCHCONTROL_WATERMARK = ('tr\u00edch t\u1eeb Google'); 
var _UDS_MSG_SEARCHER_CONFIG_SET_LOCATION = ('\u0110\u1ecba \u0111i\u1ec3m t\u00ecm ki\u1ebfm'); 
var _UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP = ('V\u00f4 hi\u1ec7u ch\u1ee9c n\u0103ng t\u00ecm \u0111\u1ecba ch\u1ec9'); 
var _UDS_MSG_SEARCHER_NEWS = ('Tin t\u1ee9c'); 
function _UDS_MSG_MINUTES_AGO(AGE_MINUTES_AGO) {return ('' + AGE_MINUTES_AGO + ' ph\u00fat tr\u01b0\u1edbc \u0111\u00e2y');} 
var _UDS_MSG_ONE_HOUR_AGO = ('1 gi\u1edd tr\u01b0\u1edbc'); 
function _UDS_MSG_HOURS_AGO(AGE_HOURS_AGO) {return ('' + AGE_HOURS_AGO + ' gi\u1edd tr\u01b0\u1edbc');} 
function _UDS_MSG_NEWS_ALL_N_RELATED(NUMBER) {return ('c\u00f3 t\u1ea5t c\u1ea3 ' + NUMBER + ' m\u1ee5c li\u00ean quan');} 
var _UDS_MSG_NEWS_RELATED = ('Nh\u1eefng m\u1ee5c c\u00f3 Li\u00ean quan'); 
var _UDS_MSG_BRANDING_STRING = ('\u0111\u01b0\u1ee3c cung c\u1ea5p b\u1edfi Google'); 
var _UDS_MSG_SORT_BY_DATE = ('X\u1ebfp theo th\u1eddi gian'); 
var _UDS_MSG_MONTH_ABBR_JAN = ('Th\u00e1ng gi\u00eang'); 
var _UDS_MSG_MONTH_ABBR_FEB = ('Th\u00e1ng hai'); 
var _UDS_MSG_MONTH_ABBR_MAR = ('Th\u00e1ng ba'); 
var _UDS_MSG_MONTH_ABBR_APR = ('Th\u00e1ng t\u01b0'); 
var _UDS_MSG_MONTH_ABBR_MAY = ('Th\u00e1ng n\u0103m'); 
var _UDS_MSG_MONTH_ABBR_JUN = ('Th\u00e1ng s\u00e1u'); 
var _UDS_MSG_MONTH_ABBR_JUL = ('Th\u00e1ng b\u1ea3y'); 
var _UDS_MSG_MONTH_ABBR_AUG = ('Th\u00e1ng t\u00e1m'); 
var _UDS_MSG_MONTH_ABBR_SEP = ('Th\u00e1ng ch\u00edn'); 
var _UDS_MSG_MONTH_ABBR_OCT = ('Th\u00e1ng m\u01b0\u1eddi'); 
var _UDS_MSG_MONTH_ABBR_NOV = ('Th\u00e1ng m\u01b0\u1eddi m\u1ed9t'); 
var _UDS_MSG_MONTH_ABBR_DEC = ('Th\u00e1ng m\u01b0\u1eddi hai'); 
var _UDS_MSG_DIRECTIONS = ('c\u00e1c h\u01b0\u1edbng'); 
var _UDS_MSG_CLEAR_RESULTS = ('xo\u00e1 c\u00e1c k\u1ebft qu\u1ea3'); 
var _UDS_MSG_SHOW_ONE_RESULT = ('hi\u1ec3n th\u1ecb m\u1ed9t k\u1ebft qu\u1ea3'); 
var _UDS_MSG_SHOW_MORE_RESULTS = ('hi\u1ec3n th\u1ecb th\u00eam nhi\u1ec1u k\u1ebft qu\u1ea3'); 
var _UDS_MSG_SHOW_ALL_RESULTS = ('hi\u1ec3n th\u1ecb t\u1ea5t c\u1ea3 k\u1ebft qu\u1ea3'); 
var _UDS_MSG_SETTINGS = ('thi\u1ebft l\u1eadp'); 
var _UDS_MSG_SEARCH = ('t\u00ecm ki\u1ebfm'); 
var _UDS_MSG_SEARCH_UC = ('T\u00ecm ki\u1ebfm'); 
var _UDS_MSG_POWERED_BY = ('\u0111\u01b0\u1ee3c cung c\u1ea5p b\u1edfi'); 
function _UDS_MSG_LOCAL_ATTRIBUTION(LOCAL_RESULTS_PROVIDER) {return ('Danh m\u1ee5c kinh doanh \u0111\u01b0\u1ee3c cung c\u1ea5p b\u1edfi ' + LOCAL_RESULTS_PROVIDER);} 
var _UDS_MSG_SEARCHER_BOOK = ('S\u00e1ch'); 
function _UDS_MSG_FOUND_ON_PAGE(FOUND_ON_PAGE) {return ('Trang ' + FOUND_ON_PAGE);} 
function _UDS_MSG_TOTAL_PAGE_COUNT(PAGE_COUNT) {return ('' + PAGE_COUNT + ' trang');} 
var _UDS_MSG_SEARCHER_BY = ('theo'); 
var _UDS_MSG_SEARCHER_CODE = ('Ma\u00f5'); 
var _UDS_MSG_UNKNOWN_LICENSE = ('Gia\u00e1y phe\u00f9p vo\u00e2 danh'); 
var _UDS_MSG_SEARCHER_GSA = ('T\u00ecm \u00f6\u00f9ng du\u00efng'); 
var _UDS_MSG_SEARCHCONTROL_MORERESULTS = ('The\u00e2m ke\u00e1t qua\u00fb'); 
var _UDS_MSG_SEARCHCONTROL_PREVIOUS = ('Tr\u00f6\u00f4\u00f9c \u00f1a\u00e2y'); 
var _UDS_MSG_SEARCHCONTROL_NEXT = ('Ke\u00e1 tie\u00e1p'); 
var _UDS_MSG_GET_DIRECTIONS = ('L\u1ea5y h\u01b0\u1edbng'); 
var _UDS_MSG_GET_DIRECTIONS_TO_HERE = ('\u0110\u1ebfn \u0111\u00e2y'); 
var _UDS_MSG_GET_DIRECTIONS_FROM_HERE = ('T\u1eeb \u0111\u00e2y'); 
var _UDS_MSG_CLEAR_RESULTS_UC = ('X\u0129a c\u00e1c k\u1ebft qu\u1ea3'); 
var _UDS_MSG_SEARCH_THE_MAP = ('t\u00ecm ki\u1ebfm b\u1ea3n \u0111\u1ed3'); 
var _UDS_MSG_SCROLL_THROUGH_RESULTS = ('cu\u1ed9n qua c\u00e1c k\u1ebft qu\u1ea3'); 
var _UDS_MSG_EDIT_TAGS = ('hi\u1ec7u ch\u1ec9nh th\u1ebb'); 
var _UDS_MSG_TAG_THIS_SEARCH = ('g\u1eafn th\u1ebb vi\u1ec7c t\u00ecm ki\u1ebfm n\u00e0y'); 
var _UDS_MSG_SEARCH_STRING = ('t\u00ecm ki\u1ebfm chu\u1ed7i'); 
var _UDS_MSG_OPTIONAL_LABEL = ('nh\u00e3n t\u00f9y ch\u1ecdn'); 
var _UDS_MSG_DELETE = ('x\u00f3a'); 
var _UDS_MSG_DELETED = ('\u0111\u00e3 x\u00f3a'); 
var _UDS_MSG_CANCEL = ('h\u1ee7y'); 
var _UDS_MSG_UPLOAD_YOUR_VIDEOS = ('T\u1ea3i \u0111o\u1ea1n video c\u1ee7a b\u1ea1n l\u00ean'); 
var _UDS_MSG_IM_DONE_WATCHING = ('T\u00f4i \u0111ang xem \u0111o\u1ea1n video'); 
var _UDS_MSG_CLOSE_VIDEO_PLAYER = ('\u0111\u00f3ng m\u00e1y ch\u01a1i video'); 
var _UDS_MSG_NO_RESULTS = ('Kh\u00f4ng c\u00f3 K\u1ebft qu\u1ea3 n\u00e0o'); 
var _UDS_MSG_LINKEDCSE_ERROR_RESULTS = ('C\u00f4ng c\u1ee5 T\u00ecm ki\u1ebfm Tu\u1ef3 ch\u1ec9nh n\u00e0y \u0111ang t\u1ea3i.  H\u00e3y th\u1eed l\u1ea1i sau v\u00e0i gi\u00e2y n\u1eefa.'); 
var _UDS_MSG_COUPONS = ('C\u00e1c phi\u1ebfu th\u01b0\u1edfng'); 
var _UDS_MSG_BACK = ('quay l\u1ea1i'); 
var _UDS_MSG_SUBSCRIBE = ('\u0110\u0103ng k\u00fd'); 
var _UDS_MSG_SEARCHER_PATENT = ('B\u1eb1ng s\u00e1ng ch\u1ebf'); 
var _UDS_MSG_USPAT = ('B\u1eb1ng s\u00e1ng ch\u1ebf M\u1ef9'); 
var _UDS_MSG_USPAT_APP = ('\u1ee8ng d\u1ee5ng B\u1eb1ng s\u00e1ng ch\u1ebf M\u1ef9'); 
var _UDS_MSG_PATENT_FILED = ('\u0110\u00e3 s\u1eafp x\u1ebfp'); 
var _UDS_MSG_ADS_BY_GOOGLE = ('Qu\u1ea3ng c\u00e1o t\u1eeb Google'); 
var _UDS_MSG_SET_DEFAULT_LOCATION = ('\u0110\u1eb7t v\u1ecb tr\u00ed m\u1eb7c \u0111\u1ecbnh'); 
var _UDS_MSG_NEWSCAT_TOPSTORIES = ('Tin ba\u0300i Ha\u0300ng \u0111\u00e2\u0300u'); 
var _UDS_MSG_NEWSCAT_WORLD = ('Th\u1ebf gi\u1edbi'); 
var _UDS_MSG_NEWSCAT_NATION = ('Qu\u1ed1c gia'); 
var _UDS_MSG_NEWSCAT_BUSINESS = ('Kinh doanh'); 
var _UDS_MSG_NEWSCAT_SCITECH = ('Khoa h\u1ecdc/C\u00f4ng ngh\u1ec7'); 
var _UDS_MSG_NEWSCAT_ENTERTAINMENT = ('Gi\u1ea3i tr\u00ed'); 
var _UDS_MSG_NEWSCAT_HEALTH = ('S\u1ee9c kho\u1ebb'); 
var _UDS_MSG_NEWSCAT_SPORTS = ('Th\u1ec3 thao'); 
var _UDS_MSG_NEWSCAT_POLITICS = ('Ch\u00ednh tr\u1ecb');
var b=true,f=null,h=false,i=encodeURIComponent,k=google_exportSymbol,aa=_UDS_CONST_SHORT_DATE_PATTERN,m=window,n=undefined,o=document,p=Math,ba=navigator,ca=parseInt,da=parseFloat,ea=_UDS_CONST_LOCALE,fa=decodeURIComponent;function ga(a,c){return a.input=c}function ha(a,c){return a.width=c}function q(a,c){return a.innerHTML=c}function ia(a,c){return a.value=c}function ja(a,c){return a.type=c}function s(a,c){return a.title=c}function t(a,c){return a.className=c}
function ka(a,c){return a.checked=c}function la(a,c){return a.target=c}function ma(a,c){return a.onclick=c}function na(a,c){return a.display=c}function oa(a,c){return a.execute=c}function pa(a,c){return a.height=c}
var v="appendChild",qa="push",ra="clearTimeout",w="input",x="width",sa="submit",ta="round",y="replace",ua="floor",va="content",z="getElementById",wa="offsetWidth",A="value",C="match",xa="focus",D="createElement",ya="firstChild",za="setAttribute",Aa="cloneNode",Ba="type",Ca="ServiceBase",Da="getTime",E="length",Ea="title",F="prototype",H="cursor",Fa="className",Ga="Version",Ha="checked",Ia="setTimeout",Ja="split",Ka="offsetParent",La="location",Ma="getComputedStyle",I="style",Na="close",Oa="body",
Pa="removeChild",J="search",K="call",L="loader",Qa="currentStyle",Ra="themes",Sa="apply",Ta="parentNode",Ua="CurrentLocale",M="execute",Va="height",Wa="join",Xa="toLowerCase",Ya="event",N;if(!google[J].NoOldNames){k("UDS_ServiceBase",google[L][Ca]);k("UDS_OriginalAppPath",google[L].OriginalAppPath);k("UDS_ApiKey",google[L].ApiKey);k("UDS_KeyVerified",google[L].KeyVerified);k("UDS_LoadFailure",google[L].LoadFailure);k("UDS_CurrentLocale",ea);k("UDS_ShortDatePattern",aa);k("UDS_Version",google[J][Ga]);k("UDS_JSHash",google[J].JSHash)}if(!O)var O=k;if(!P)var P=google_exportProperty;var Q={};Q.blank="&nbsp;";Q.image=_UDS_MSG_SEARCHER_IMAGE;Q.web=_UDS_MSG_SEARCHER_WEB;Q.blog=_UDS_MSG_SEARCHER_BLOG;Q.video=_UDS_MSG_SEARCHER_VIDEO;Q.local=_UDS_MSG_SEARCHER_LOCAL;Q.news=_UDS_MSG_SEARCHER_NEWS;Q.book=_UDS_MSG_SEARCHER_BOOK;Q.patent="Patent";Q["ads-by-google"]=_UDS_MSG_ADS_BY_GOOGLE;Q.cse="Custom Search Control";Q.save=_UDS_MSG_SEARCHCONTROL_SAVE;Q.keep=_UDS_MSG_SEARCHCONTROL_KEEP;Q.include=_UDS_MSG_SEARCHCONTROL_INCLUDE;Q.copy=_UDS_MSG_SEARCHCONTROL_COPY;Q.close=_UDS_MSG_SEARCHCONTROL_CLOSE;
Q["sponsored-links"]=_UDS_MSG_SEARCHCONTROL_SPONSORED_LINKS;Q["see-more"]=_UDS_MSG_SEARCHCONTROL_SEE_MORE;Q.watermark=_UDS_MSG_SEARCHCONTROL_WATERMARK;Q["search-location"]=_UDS_MSG_SEARCHER_CONFIG_SET_LOCATION;Q["disable-address-lookup"]=_UDS_MSG_SEARCHER_CONFIG_DISABLE_ADDRESS_LOOKUP;Q["sort-by-date"]=_UDS_MSG_SORT_BY_DATE;Q.pbg=_UDS_MSG_BRANDING_STRING;Q["n-minutes-ago"]=_UDS_MSG_MINUTES_AGO;Q["n-hours-ago"]=_UDS_MSG_HOURS_AGO;Q["one-hour-ago"]=_UDS_MSG_ONE_HOUR_AGO;Q["all-n-related"]=_UDS_MSG_NEWS_ALL_N_RELATED;
Q["related-articles"]=_UDS_MSG_NEWS_RELATED;Q["page-count"]=_UDS_MSG_TOTAL_PAGE_COUNT;var R=[];R[0]=_UDS_MSG_MONTH_ABBR_JAN;R[1]=_UDS_MSG_MONTH_ABBR_FEB;R[2]=_UDS_MSG_MONTH_ABBR_MAR;R[3]=_UDS_MSG_MONTH_ABBR_APR;R[4]=_UDS_MSG_MONTH_ABBR_MAY;R[5]=_UDS_MSG_MONTH_ABBR_JUN;R[6]=_UDS_MSG_MONTH_ABBR_JUL;R[7]=_UDS_MSG_MONTH_ABBR_AUG;R[8]=_UDS_MSG_MONTH_ABBR_SEP;R[9]=_UDS_MSG_MONTH_ABBR_OCT;R[10]=_UDS_MSG_MONTH_ABBR_NOV;R[11]=_UDS_MSG_MONTH_ABBR_DEC;Q["month-abbr"]=R;Q.directions=_UDS_MSG_DIRECTIONS;
Q["clear-results"]=_UDS_MSG_CLEAR_RESULTS;Q["show-one-result"]=_UDS_MSG_SHOW_ONE_RESULT;Q["show-more-results"]=_UDS_MSG_SHOW_MORE_RESULTS;Q["show-all-results"]=_UDS_MSG_SHOW_ALL_RESULTS;Q.settings=_UDS_MSG_SETTINGS;Q.search=_UDS_MSG_SEARCH;Q["search-uc"]=_UDS_MSG_SEARCH_UC;Q["powered-by"]=_UDS_MSG_POWERED_BY;Q.sa=_UDS_MSG_SEARCHER_GSA;Q.by=_UDS_MSG_SEARCHER_BY;Q.code=_UDS_MSG_SEARCHER_CODE;Q["unknown-license"]=_UDS_MSG_UNKNOWN_LICENSE;Q["more-results"]=_UDS_MSG_SEARCHCONTROL_MORERESULTS;
Q.previous=_UDS_MSG_SEARCHCONTROL_PREVIOUS;Q.next=_UDS_MSG_SEARCHCONTROL_NEXT;Q["get-directions"]=_UDS_MSG_GET_DIRECTIONS;Q["to-here"]=_UDS_MSG_GET_DIRECTIONS_TO_HERE;Q["from-here"]=_UDS_MSG_GET_DIRECTIONS_FROM_HERE;Q["clear-results-uc"]=_UDS_MSG_CLEAR_RESULTS_UC;Q["search-the-map"]=_UDS_MSG_SEARCH_THE_MAP;Q["scroll-results"]=_UDS_MSG_SCROLL_THROUGH_RESULTS;Q["edit-tags"]=_UDS_MSG_EDIT_TAGS;Q["tag-search"]=_UDS_MSG_TAG_THIS_SEARCH;Q["search-string"]=_UDS_MSG_SEARCH_STRING;Q["optional-label"]=_UDS_MSG_OPTIONAL_LABEL;
Q["delete"]=_UDS_MSG_DELETE;Q.deleted=_UDS_MSG_DELETED;Q.cancel=_UDS_MSG_CANCEL;Q["upload-video"]=_UDS_MSG_UPLOAD_YOUR_VIDEOS;Q["im-done"]=_UDS_MSG_IM_DONE_WATCHING;Q["close-player"]=_UDS_MSG_CLOSE_VIDEO_PLAYER;Q["no-results"]=_UDS_MSG_NO_RESULTS;Q["linked-cse-error-results"]=_UDS_MSG_LINKEDCSE_ERROR_RESULTS;Q.back=_UDS_MSG_BACK;Q.subscribe=_UDS_MSG_SUBSCRIBE;Q["us-pat"]="US Pat.";Q["us-pat-app"]="US Pat. App";Q["us-pat-filed"]="Filed";function Za(a,c){var d=function(){};d.prototype=c[F];a.prototype=new d;a[F].Qh=function(e){var g=Array[F].splice[Sa](arguments,[1,arguments[E]]);return e[Sa](a,g)}}var _json_cache_defeater_=(new Date)[Da](),_json_request_require_prep=b;function $a(a,c){var d;if(d=ab("msie"))d="msie 6.0"in bb?bb["msie 6.0"]:bb["msie 6.0"]=ba.appVersion[Xa]().indexOf("msie 6.0")!=-1;d?m[Ia](S(this,cb,[a,c]),0):cb(a,c)}function db(a){_json_request_require_prep=h;$a(a,f);_json_request_require_prep=b}
function cb(a,c){var d=o.getElementsByTagName("head")[0];d||(d=o[Oa][Ta][v](o[D]("head")));var e=o[D]("script");ja(e,"text/javascript");e.charset="utf-8";var g=_json_request_require_prep?a+"&key="+google[L].ApiKey+"&v="+c:a;if(ab("msie")||ab("safari")||ab("konqueror"))g=g+"&nocache="+_json_cache_defeater_++;e.src=g;var j=function(){e.onload=f;e[Ta][Pa](e);delete e};g=function(l){l=(l?l:m[Ya]).target?(l?l:m[Ya]).target:(l?l:m[Ya]).srcElement;if(l.readyState=="loaded"||l.readyState=="complete"){l.onreadystatechange=
f;j()}};if(ba.product=="Gecko")e.onload=j;else e.onreadystatechange=g;d[v](e)}function eb(a,c){return function(){return c[Sa](a,arguments)}}function S(a,c,d){return function(){return c[Sa](a,d)}}function fb(a){for(;a[ya];)a[Pa](a[ya])}function gb(a,c){if(a)try{fb(a);a[v](c)}catch(d){}return c}function T(a,c){try{a[v](c)}catch(d){}return c}function hb(a){return o.createTextNode(a?a:"")}function U(a,c){var d=o[D]("div");if(a)q(d,a);if(c)t(d,c);return d}
function ib(a,c){var d=o[D]("div");a&&T(d,hb(a));if(c)t(d,c);return d}function W(a){var c=o[D]("div");if(a)t(c,a);return c}function kb(a,c){var d=o[D]("span");a&&T(d,hb(a));if(c)t(d,c);return d}function lb(a,c,d){var e=o[D]("table");e[za]("cellSpacing",a?a:0);e[za]("cellPadding",c?c:0);if(d)t(e,d);return e}function mb(a,c,d){(a=a.insertRow(-1))||alert(a);for(var e=0;e<c;e++)X(a,d);return a}function X(a,c){var d=a.insertCell(-1);if(c)t(d,c);return d}
function nb(a){var c=o[D]("td");if(a)t(c,a);return c}function ob(a,c,d,e){var g=o[D]("img");g.src=a;if(c)ha(g,c);if(d)pa(g,d);if(e)t(g,e);return g}function pb(a,c,d,e,g){var j=o[D]("a");j.href=a;if(c)e?T(j,kb(c,e)):T(j,hb(c));if(d)la(j,d);if(g)s(j,g);return j}function Y(a,c,d,e,g){var j=U(f,e),l=o[D]("a");l.href=a;q(l,c);if(e)t(l,e);if(d)la(l,d);if(g)s(l,g);j[v](l);return j}function qb(a){var c=o[D]("form");if(a)t(c,a);return c}
function rb(a,c){var d=o[D]("input");ja(d,"submit");ia(d,a);if(c)t(d,c);return d}function sb(a,c,d){var e=o[D]("input");e[za]("autoComplete","off");ja(e,"text");if(a==-1)Z(e,"util-css-expand");else e.size=a>0?a:10;c&&Z(e,c);if(d)ia(e,d);return e}function tb(a,c,d,e){var g=o[D]("input");ja(g,"checkbox");g.name=a;ia(g,c);if(e)t(g,e);if(d)ka(g,d);return g}function Z(a,c){var d;a:{if(!(a==f||a[Fa]==f)){d=a[Fa][Ja](" ");for(var e=0;e<d[E];e++)if(d[e]==c){d=b;break a}}d=h}d||(a.className+=" "+c)}
function $(a,c){if(a[Fa]!=f){for(var d=a[Fa][Ja](" "),e=[],g=h,j=0;j<d[E];j++)if(d[j]!=c)d[j]&&e[qa](d[j]);else g=b;if(g)t(a,e[Wa](" "))}}var ub="",vb={pg:{Zh:1,ci:1,li:1,id:1,mi:1,"in":1,oi:1,qi:1,ri:1,si:1,vi:1,Ei:1,Ui:1,Yi:1,Zi:1,dj:1,ej:1,hj:1},$h:{Rh:1,Th:1,Vh:1,Wh:1,Xh:1,Yh:1,pg:1,di:1,"do":1,fi:1,gi:1,hi:1,ii:1,ji:1,ki:1,pi:1,wi:1,xi:1,yi:1,zi:1,Ai:1,Bi:1,Ci:1,Di:1,Gi:1,Hi:1,Ii:1,Ji:1,Ki:1,Li:1,Oi:1,Ri:1,Ti:1,Vi:1,Wi:1,Xi:1,bj:1,cj:1,gj:1},Fi:{Sh:1}};
function ab(a){if(a in wb)return wb[a];return wb[a]=ba.userAgent[Xa]().indexOf(a)!=-1}var wb={},bb={},xb,yb;if(m.Ph){xb=b;if(m.XMLHttpRequest)yb=b}function zb(a){this.vc=a+"branding";this.hc=a+"branding-vertical";this.ni=a+"branding-img";this.aj=a+"branding-user-defined";this.Ue=a+"branding-img-noclear";this.og=a+"branding-clickable";this.text=a+"branding-text"};var Ab=f,Bb=function(){if(Ab)return Ab;var a=o[D]("div");ha(a[I],"1px");pa(a[I],"1px");a[I].border="1px solid black";a[I].padding="1px";a[I].visibility="hidden";o[Oa][v](a);var c=a[wa];o[Oa][Pa](a);return Ab=c==5};function Db(a){return da(a[y]("px",""))||0}
function Eb(a,c){if(typeof a=="string")a=o[z](a);var d=o.defaultView||{},e=c?a.offsetHeight:a[wa],g=c?["Top","Bottom"]:["Right","Left"],j;j=Bb()?["margin"]:["border","margin","padding"];var l=j[E],r=g[E];if(d&&d[Ma]){var u=d[Ma](a,h);for(d=0;d<l;d++)for(var B=0;B<r;B++)e+=Db(u.getPropertyValue([j[d],g[B][Xa]()][Wa]("-")))}else{u=a[Qa];if(!Bb())for(B=0;B<r;B++)e+=Db(u[["border",g[B],"Width"][Wa]("")]);for(d=1;d<l;d++)for(B=0;B<r;B++)e+=Db(u[[j[d],g[B]][Wa]("")])}return e};google[J].a=function(){this.la=this.ai=f;this.dd=this.Mh=0;this.Qe=b;this.T={width:100,height:75};this.Oa=google[J].a.kb;this.af=1;this.Y(google[J].a.ia);this.He();this.gwsUrl=this.z=this.L=this.Qi=this.A=this.Vb=this.Mb=this.ib=this.Tc=this.ec=this.Ec=this.Cc=f;this.ya=[];var a;if(typeof m==="object"&&m[La]&&m[La].hostname&&m[La].hostname!=""){if(ub==""){var c=m[La].hostname[Xa]()[Ja](".");if(c[E]<2)ub=".com";a=c.pop();c=c.pop();ub=a[E]==2?vb[c]&&vb[c][a]==1?"."+c+"."+a:"."+a:".com"}a=ub}else a=
".com";this.Se=a;this.Ab=this.sb=f};O("google.search.Search",google[J].a);google[J].a.jd=google[L][Ca];P(google[J].a,"BASE",google[J].a.jd);google[J].a.eg=/style=([^&]*)/;google[J].a.ta="large";P(google[J].a,"LARGE_RESULTSET",google[J].a.ta);google[J].a.ia="small";P(google[J].a,"SMALL_RESULTSET",google[J].a.ia);google[J].a.Ta="filtered_cse";P(google[J].a,"FILTERED_CSE_RESULTSET",google[J].a.Ta);google[J].a.Mf=8;P(google[J].a,"LARGE_RESULTS",google[J].a.Mf);google[J].a.bg=4;
P(google[J].a,"SMALL_RESULTS",google[J].a.bg);google[J].a.Gf=10;P(google[J].a,"FILTERED_CSE_RESULTS",google[J].a.Gf);google[J].a.Rd=5E3;P(google[J].a,"KEEP_SWEEPER_DELAY",google[J].a.Rd);google[J].a.Pf="_top";P(google[J].a,"LINK_TARGET_TOP",google[J].a.Pf);google[J].a.Of="_self";P(google[J].a,"LINK_TARGET_SELF",google[J].a.Of);google[J].a.Nf="_parent";P(google[J].a,"LINK_TARGET_PARENT",google[J].a.Nf);google[J].a.kb="_blank";P(google[J].a,"LINK_TARGET_BLANK",google[J].a.kb);google[J].a.lb="order-by-relevance";
P(google[J].a,"ORDER_BY_RELEVANCE",google[J].a.lb);google[J].a.ua="order-by-date";P(google[J].a,"ORDER_BY_DATE",google[J].a.ua);google[J].a.Ud="order-by-ascending-date";P(google[J].a,"ORDER_BY_ASCENDING_DATE",google[J].a.Ud);google[J].a.Nb="restrict-type";P(google[J].a,"RESTRICT_TYPE",google[J].a.Nb);google[J].a.kc="restrict-safesearch";P(google[J].a,"RESTRICT_SAFESEARCH",google[J].a.kc);google[J].a.mc="active";P(google[J].a,"SAFESEARCH_STRICT",google[J].a.mc);google[J].a.lc="off";
P(google[J].a,"SAFESEARCH_OFF",google[J].a.lc);google[J].a.ge="moderate";P(google[J].a,"SAFESEARCH_MODERATE",google[J].a.ge);google[J].a.Ua="restrict-extended";P(google[J].a,"RESTRICT_EXTENDED_ARGS",google[J].a.Ua);google[J].a.Gh=Q;P(google[J].a,"strings",google[J].a.Gh);google[J].a.Ig=function(){if(google[J].LoadArgs){var a=fa(google[J].LoadArgs)[C](google[J].a.eg);if(a&&a[1])return a[1]}return f};
google[J].a[F].fh=function(){var a=this.wa+"?hl="+google[J][Ua]+"&source=uds";a+=this.z?this.z:"&q=";return this.Ga&&this.Ga!=""?this.Ga:a};google[J].a[F].xh=function(a){this.L=a==f||a==""?f:a};P(google[J].a[F],"setQueryAddition",google[J].a[F].xh);
google[J].a[F].Ha=function(a,c,d){a=google[J].a.jd+this.Ja+"?callback="+a+"&context="+c+"&lstkp="+this.ng()+"&rsz="+this.za+"&hl="+google[J][Ua];if(this.bc)a+="&source="+i(this.bc);if(this.Se)a+="&gss="+this.Se;if(google[J].JSHash)a+="&sig="+google[J].JSHash;if(d)a+="&start="+d;return a};google[J].a[F].Bh=function(a){this.bc=a};P(google[J].a[F],"setSearcherSrc",google[J].a[F].Bh);google[J].a[F].Hb=function(a){this.Oa=a};P(google[J].a[F],"setLinkTarget",google[J].a[F].Hb);N=google[J].a[F];
N.v=function(){return this.Oa&&this.Oa!=""?this.Oa:f};N.Ng=function(){this.Mh++;this.dd++;this.Vb&&m[ra](this.Vb);this.Vb=m[Ia](S(this,this[M],[f]),google[J].a.Rd)};N.ng=function(){m[ra](this.Vb);var a=this.dd;this.dd=0;return a};N.Mc=function(){if(this.Cc==f)this.Cc="gsc-"+this.A+"Result";return this.Cc};N.va=function(){if(this.Ec==f)this.Ec="gs-"+this.A+"Result";return this.Ec};N.Kg=function(){if(this.ec==f)this.ec=Q[this.A];return this.ib?this.ib:this.ec};
N.Hg=function(){if(this.Tc==f)this.Tc=Q[this.A];return this.ib?this.ib:this.Tc};N.Jg=function(){return this.za};P(google[J].a[F],"getResultSetSize",google[J].a[F].Jg);google[J].a[F].Y=function(a){if(a>0&&a<=8)this.za=a;else switch(a){case google[J].a.ta:this.za=google[J].a.ta;break;default:case google[J].a.ia:this.za=google[J].a.ia}};P(google[J].a[F],"setResultSetSize",google[J].a[F].Y);
oa(google[J].a[F],function(a){var c=(new Date)[Da]();this.cd=c%100==1?c:-1;c=this.ma(a,f,f);c+=this.ub?"&"+this.ub:"";if(m._googleudsextrastuff)c+=m._googleudsextrastuff;this.cursor=f;this.Ye=a;$a(c,google[J][Ga]);if(this.ya&&this.ya[E]>0)for(c=0;c<this.ya[E];c++)this.ya[c][M](a)});P(google[J].a[F],"execute",google[J].a[F][M]);google[J].a[F].Te=function(a){if(this[H]&&a<this[H].pages[E]){a=this.ma(this.Ye,f,f,this[H].pages[a].start);this.cursor=f;$a(a,google[J][Ga])}};
P(google[J].a[F],"gotoPage",google[J].a[F].Te);google[J].a[F].gg=function(a){this.ya&&this.ya[qa](a)};P(google[J].a[F],"addRelatedSearcher",google[J].a[F].gg);google[J].a[F].Gg=function(a,c,d){return this.ma(a,c,d)+"&key="+google[L].ApiKey+"&v="+google[J][Ga]};P(google[J].a[F],"getExecuteUrl",google[J].a[F].Gg);google[J].a[F].Da=function(a){var c=Y("http://code.google.com/apis/ajaxsearch/faq.html",Q.watermark+" - "+this.qg(),"_blank","gs-watermark");T(a,c)};
google[J].a[F].qg=function(){var a=new Date;return a.getMonth()+1+"/"+a.getFullYear()};google[J].a[F].bb=function(a){var c;c=a.getFullYear();var d=a.getMonth(),e=Q["month-abbr"][d];a=a.getDate();if(a<10)a="0"+a;switch(google[J].ShortDatePattern){case "MDY":c=e+" "+a+", "+c;break;case "YMD":if(google[J][Ua]=="zh-CN"||google[J][Ua]=="zh-TW"||google[J][Ua]=="ja"||google[J][Ua]=="ko"){e=Fb[google[J][Ua]];c=c+e.year+(d+1)+e.month+a+e.day}else c=c+" "+e+" "+a;break;default:case "DMY":c=a+" "+e+" "+c}return c};
P(google[J].a[F],"formatToShortDate",google[J].a[F].bb);var Fb={"zh-CN":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},"zh-TW":{month:" \u6708 ",year:" \u5e74 ",day:" \u65e5 "},ja:{month:"\u6708",year:"\u5e74",day:"\u65e5"},ko:{month:" \uc6d4 ",year:" \ub144 ",day:" \uc77c "}};google[J].a.Sd=36E5;google[J].a.Xf=6E4;google[J].a.Wf=864E5;
google[J].a[F].Kc=function(a){var c=(new Date)[Da](),d=a[Da]();if(c<d)return Q["n-minutes-ago"](2);c=c-d;if(c<google[J].a.Sd){a=p[ua](c/google[J].a.Xf);a=a<=1?2:a;return Q["n-minutes-ago"](a)}if(c<google[J].a.Wf){a=p[ua](c/google[J].a.Sd);if(a<=1)return Q["one-hour-ago"];else{a=a;return Q["n-hours-ago"](a)}}return this.bb(a)};P(google[J].a[F],"formatToRelativeDate",google[J].a[F].Kc);google[J].a[F].He=function(){this.Mi=this.gwsUrl=f;this.results=[]};P(google[J].a[F],"clearResults",google[J].a[F].He);
google[J].a[F].zg=function(){this.Ie&&this.Ie();if(this.cd!=-1){google[L].recordStat("asa_"+this.A,"req."+((new Date)[Da]()-this.cd),b);this.cd=-1}};
google[J].a[F].aa=function(a,c,d,e){if(!(a==f&&c==204)){this.gwsUrl=f;if(this.results&&this.results[E]>0)for(var g=0;g<this.results[E];g++)if(this.results[g].html){var j=this.results[g].html;Gb||(Gb=o[D]("DIV"));Gb[v](j);q(Gb,"")}if(a&&a.results&&a.results[E]>0){this.results=a.results;if(a[H]&&a[H].moreResultsUrl)this.gwsUrl=this.Ga&&this.Ga!=""?this.Ga:a[H].moreResultsUrl;else if(this.z&&this.wa)this.gwsUrl=this.fh()}else this.results=[];this.completionStatus=c;this.hashStatus=e;this.bi=d;this.ff=
a&&a.resultAttribution&&a.resultAttribution!=f&&a.resultAttribution!=""?a.resultAttribution:f;if(a&&a[H]&&a[H].pages&&a[H].pages[E]>0)this.cursor=a[H];else typeof this[H]!="undefined"&&delete this[H];if(a&&a.context)this.context=a.context;else typeof this.context!="undefined"&&delete this.context;if(a&&a.promotions)this.promotions=a.promotions;else typeof this.promotions!="undefined"&&delete this.promotions;if(a&&a.omittedResults)this.omittedResults=a.omittedResults;else typeof this.omittedResults!=
"undefined"&&delete this.omittedResults;this.Qe&&this.jg();this.zg()}};P(google[J].a[F],"onSearchComplete",google[J].a[F].aa);google[J].a[F].Re=function(){var a=f;if(this.ff)a=U(this.ff,"gs-results-attribution");return a};P(google[J].a[F],"getAttribution",google[J].a[F].Re);google[J].a[F].jg=function(){var a,c;for(a=0;a<this.results[E];a++){c=this.results[a];this.I(c)}};google[J].a[F].Jb=function(a,c,d){d||(d=[f]);this.Ie=S(a,c,d)};P(google[J].a[F],"setSearchCompleteCallback",google[J].a[F].Jb);
google[J].a.qa=function(a,c){var d=h,e;if(a[E])for(var g=0;g<a[E];g++)if(a[g]==f){a[g]=c;e=g;d=b;break}if(!d){e=a[E];a[qa](c)}return e};P(google[J].a,"AllocateCompletionMapContext",google[J].a.qa);google[J].a[F].Lb=function(a){this.ib=a};P(google[J].a[F],"setUserDefinedLabel",google[J].a[F].Lb);google[J].a[F].Dh=function(a){this.Mb=a};P(google[J].a[F],"setUserDefinedClassSuffix",google[J].a[F].Dh);google[J].a[F].vh=function(){this.Qe=h};P(google[J].a[F],"setNoHtmlGeneration",google[J].a[F].vh);
google[J].a.gb=function(a,c,d,e,g){var j=p.min(p.min(d[x]/a,d[Va]/c),1),l={};ha(l,p[ta](a*j));pa(l,p[ta](c*j));if(e){ha(e,l[x]);pa(e,l[Va]);if(g)e[I].left=(d[x]-l[x])/2+"px"}return l};P(google[J].a,"scaleImage",google[J].a.gb);google[J].a.xe=1;P(google[J].a,"VERTICAL_BRANDING",google[J].a.xe);google[J].a.Hf=2;P(google[J].a,"HORIZONTAL_BRANDING",google[J].a.Hf);
google[J].a.Cg=function(a,c,d){var e=c&&c==google[J].a.xe,g=new zb("gsc-");c=W(g.vc);var j=lb(f,f,g.vc);T(c,j);e=!e;if(!e){Z(c,g.hc);Z(j,g.hc)}var l=mb(j,0),r,u;if(e)u=r=l;else{r=l;u=mb(j,0)}var B="/css/small-logo.png",G=51;l=15;if(d)if(typeof d=="string")if(d[C](/^http:\/\/www\.youtube\.com/)){B="/css/youtube-logo-55x24.png";G=55;l=24;Z(c,g.vc+"-youtube");if(!e){Z(c,g.hc+"-youtube");Z(j,g.hc+"-youtube")}}e=X(r,g.text);j=X(u,g.Ue);r=U(Q["powered-by"],g.text);B=google[L][Ca]+B;G=G;l=l;u=g.Ue;if(xb&&
!yb){u=W(u);u[I].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+B+'")';ha(u[I],G+"px");pa(u[I],l+"px")}else u=ob(B,f,f,u);l=u;T(e,r);if(d){e="http://www.google.com";if(typeof d=="string"&&(d[C](/^http:\/\/[a-z]*\.google\.com/)||d[C](/^http:\/\/www\.youtube\.com/)))e=d;d=pb(e,f,"_BLANK");t(d,g.og);T(d,l);T(j,d)}else T(j,l);if(a){a=typeof a=="string"?o[z](a):a;fb(a);T(a,c)}return c};P(google[J].a,"getBranding",google[J].a.Cg);
google[J].a.setOnLoadCallback=function(a,c){google.setOnLoadCallback(a,c)};P(google[J].a,"setOnLoadCallback",google[J].a.setOnLoadCallback);var Gb;google[J].a[F].Ag=function(a){var c=this.sb;if(a)c=a;a={};var d=W(this.va());Z(d,"gs-result");Z(d,"gs-error-result");c=U(c,"gs-snippet");T(d,c);a.html=d;return a};google[J].a[F].Bg=function(a){var c=this.Ab;if(a)c=a;a={};var d=W(this.va());Z(d,"gs-result");Z(d,"gs-no-results-result");c=U(c,"gs-snippet");T(d,c);a.html=d;return a};
k("google.search.CurrentLocale",ea);k("google.search.ShortDatePattern",aa);google[J].s=function(){google[J].a[K](this);this.A="blog";this.Ja="/GblogSearch";this.wa="http://blogsearch.google.com/blogsearch";this.m=f;this.U=h;this.$a=b;this.la=eb(this,google[J].s[F].xa);this.Za="gsc-blogConfig";this.q=f};O("google.search.BlogSearch",google[J].s);Za(google[J].s,google[J].a);google[J].s.H="GblogSearch";P(google[J].s,"RESULT_CLASS",google[J].s.H);google[J].s.p=[];google[J].s.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].s.p[j];google[J].s.p[j]=f;a.aa(c,d,e,g)};
P(google[J].s,"RawCompletion",google[J].s.N);google[J].s[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].s.p,this):d;c=this.Ha(c==f?"google.search.BlogSearch.RawCompletion":c,d,e);if(a){a=a;if(this.L)a=a+" "+this.L;if(this.m)a=a+" blogurl:"+this.m;a="&q="+i(a);if(this.U)a+="&scoring=d";c+=a;this.z=a}return c};
google[J].s[F].I=function(a){a.html&&delete a.html;var c=W(this.va());Z(c,"gs-result");var d;d=Y(a.postUrl,a[Ea],this.v(),"gs-title");T(c,d);d=new Date(a.publishedDate);d=U(this.bb(d),"gs-publishedDate");T(c,d);d=new Date(a.publishedDate);d=U(this.Kc(d),"gs-relativePublishedDate");T(c,d);d=U(a[va],"gs-snippet");T(c,d);d=Y(a.blogUrl,a.blogUrl,this.v(),"gs-visibleUrl");T(c,d);a.html=c;this.Da(a.html)};P(google[J].s[F],"createResultHtml",google[J].s[F].I);
google[J].s[F].Ba=function(a){this.m=a==f||a==""?f:a};P(google[J].s[F],"setSiteRestriction",google[J].s[F].Ba);google[J].s[F].P=function(a){this.U=a==google[J].a.ua?b:h};P(google[J].s[F],"setResultOrder",google[J].s[F].P);
google[J].s[F].xa=function(a,c){if(c){if(this.q==f){var d=W("gsc-configSetting");this.q=tb(f,"0",this.U,"gsc-configSettingCheckbox");T(d,this.q);T(d,U(Q["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,rb(Q[Na],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.q,this.U);this.q[xa]()}else if(this.q)this.q[Ha]?this.P(google[J].a.ua):this.P(google[J].a.lb)};google[J].n=function(){google[J].a[K](this);this.A="book";this.Ja="/GbookSearch";this.wa="http://books.google.com/books";this.Ub=h;this.fd=f};O("google.search.BookSearch",google[J].n);Za(google[J].n,google[J].a);google[J].n.H="GbookSearch";P(google[J].n,"RESULT_CLASS",google[J].n.H);google[J].n.we="user-list";P(google[J].n,"USER_LIST",google[J].n.we);google[J].n.oe=1;P(google[J].n,"TYPE_ALL_BOOKS",google[J].n.oe);google[J].n.se=2;P(google[J].n,"TYPE_FULL_VIEW_BOOKS",google[J].n.se);
google[J].n.p=[];google[J].n.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].n.p[j];google[J].n.p[j]=f;a.aa(c,d,e,g)};P(google[J].n,"RawCompletion",google[J].n.N);google[J].n[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].n.p,this):d;c=this.Ha(c==f?"google.search.BookSearch.RawCompletion":c,d,e);if(a){a=a;if(this.L)a=a+" "+this.L;a="&q="+i(a);if(this.Ub)a+="&as_brr=1";if(this.fd)a=a+"&as_list="+this.fd;c+=a;this.z=a}return c};
google[J].n[F].I=function(a){a.html&&delete a.html;a.thumbnailHtml=this.Dc(a);var c=W(this.va());Z(c,"gs-result");var d=W("gs-text-box"),e=lb(),g=mb(e,0),j=X(g,"gs-image-box");g=X(g,"gs-text-box");T(j,a.thumbnailHtml[Aa](b));T(g,d);T(c,e);e=Y(a.unescapedUrl,a[Ea],this.v(),"gs-title");T(d,e);e=U(Q.by+"&nbsp;"+a.authors,"gs-author");T(d,e);e=W("gs-spacer");T(d,e);if(a.publishedYear){e=U(a.publishedYear,"gs-publishedDate");T(d,e)}if(ca(a.pageCount,10)>0){e=U("-&nbsp;"+Q["page-count"](a.pageCount),"gs-pageCount");
T(d,e)}e=Y("http://books.google.com","books.google.com",this.v(),"gs-visibleUrl");T(d,e);a.html=c;this.Da(a.html)};P(google[J].n[F],"createResultHtml",google[J].n[F].I);
google[J].n[F].Dc=function(a){var c=W("gs-image-box gs-book-image-box"),d=W("gs-row-1"),e=ob("http://books.google.com/googlebooks/pages-trans.gif",f,f,"gs-pages");T(d,e);e=ob("http://books.google.com/googlebooks/p_edge-trans.gif",f,f,"gs-page-edge");T(d,e);T(c,d);d=W("gs-row-2");e=google[J].a.gb(a.tbWidth,a.tbHeight,this.T);e=ob(a.tbUrl,e[x],e[Va],"gs-image");a=pb(a.unescapedUrl,f,this.v(),"gs-image");t(a,"gs-image");T(a,e);T(d,a);T(c,d);return c};
google[J].n[F].X=function(a,c){if(a==google[J].a.Nb)if(c)if(c==google[J].n.oe)this.Ub=h;else if(c==google[J].n.se)this.Ub=b;else this.X(a,f);else this.Ub=h;else if(a==google[J].n.we)this.fd=c&&c[C](/^[a-zA-Z0-9\-_]*$/)?c:f};P(google[J].n[F],"setRestriction",google[J].n[F].X);google[J].c=function(){google[J].a[K](this);this.af=2;this.A="image";this.Ja="/GimageSearch";this.wa="http://images.google.com/images";this.m=this.Yc=this.Jc=this.Qc=this.Oc=this.Nc=this.Pc=this.Aa=f;this.T={width:112,height:84}};O("google.search.ImageSearch",google[J].c);Za(google[J].c,google[J].a);google[J].c.H="GimageSearch";P(google[J].c,"RESULT_CLASS",google[J].c.H);google[J].c.$d="restrict-imagesize";P(google[J].c,"RESTRICT_IMAGESIZE",google[J].c.$d);google[J].c.Lf=["icon"];
P(google[J].c,"IMAGESIZE_SMALL",google[J].c.Lf);google[J].c.Kf=["small","medium","large","xlarge"];P(google[J].c,"IMAGESIZE_MEDIUM",google[J].c.Kf);google[J].c.Jf=["xxlarge"];P(google[J].c,"IMAGESIZE_LARGE",google[J].c.Jf);google[J].c.If=["huge"];P(google[J].c,"IMAGESIZE_EXTRA_LARGE",google[J].c.If);google[J].c.Yd="restrict-coloration";P(google[J].c,"RESTRICT_COLORIZATION",google[J].c.Yd);google[J].c.kd="mono";P(google[J].c,"COLORIZATION_BLACK_AND_WHITE",google[J].c.kd);google[J].c.md="gray";
P(google[J].c,"COLORIZATION_GRAYSCALE",google[J].c.md);google[J].c.ld="color";P(google[J].c,"COLORIZATION_COLOR",google[J].c.ld);google[J].c.Xd="restrict-colorfilter";P(google[J].c,"RESTRICT_COLORFILTER",google[J].c.Xd);google[J].c.vd="red";P(google[J].c,"COLOR_RED",google[J].c.vd);google[J].c.sd="orange";P(google[J].c,"COLOR_ORANGE",google[J].c.sd);google[J].c.yd="yellow";P(google[J].c,"COLOR_YELLOW",google[J].c.yd);google[J].c.rd="green";P(google[J].c,"COLOR_GREEN",google[J].c.rd);
google[J].c.wd="teal";P(google[J].c,"COLOR_TEAL",google[J].c.wd);google[J].c.od="blue";P(google[J].c,"COLOR_BLUE",google[J].c.od);google[J].c.ud="purple";P(google[J].c,"COLOR_PURPLE",google[J].c.ud);google[J].c.td="pink";P(google[J].c,"COLOR_PINK",google[J].c.td);google[J].c.xd="white";P(google[J].c,"COLOR_WHITE",google[J].c.xd);google[J].c.qd="gray";P(google[J].c,"COLOR_GRAY",google[J].c.qd);google[J].c.nd="black";P(google[J].c,"COLOR_BLACK",google[J].c.nd);google[J].c.pd="brown";
P(google[J].c,"COLOR_BROWN",google[J].c.pd);google[J].c.Zd="restrict-filetype";P(google[J].c,"RESTRICT_FILETYPE",google[J].c.Zd);google[J].c.Dd="jpg";P(google[J].c,"FILETYPE_JPG",google[J].c.Dd);google[J].c.Ed="png";P(google[J].c,"FILETYPE_PNG",google[J].c.Ed);google[J].c.Cd="gif";P(google[J].c,"FILETYPE_GIF",google[J].c.Cd);google[J].c.Bd="bmp";P(google[J].c,"FILETYPE_BMP",google[J].c.Bd);google[J].c.ae="restrict-imagetype";P(google[J].c,"RESTRICT_IMAGETYPE",google[J].c.ae);google[J].c.Gd="face";
P(google[J].c,"IMAGETYPE_FACES",google[J].c.Gd);google[J].c.Fd="clipart";P(google[J].c,"IMAGETYPE_CLIPART",google[J].c.Fd);google[J].c.Hd="lineart";P(google[J].c,"IMAGETYPE_LINEART",google[J].c.Hd);google[J].c.Id="news";P(google[J].c,"IMAGETYPE_NEWS",google[J].c.Id);google[J].c.Jd="photo";P(google[J].c,"IMAGETYPE_PHOTO",google[J].c.Jd);google[J].c.be="restrict-rights";P(google[J].c,"RESTRICT_RIGHTS",google[J].c.be);google[J].c.fe="(cc_publicdomain|cc_attribute|cc_sharealike|cc_noncommercial|cc_nonderived)";
P(google[J].c,"RIGHTS_REUSE",google[J].c.fe);google[J].c.de="(cc_publicdomain|cc_attribute|cc_sharealike|cc_nonderived).-(cc_noncommercial)";P(google[J].c,"RIGHTS_COMMERCIAL_REUSE",google[J].c.de);google[J].c.ee="(cc_publicdomain|cc_attribute|cc_sharealike|cc_noncommercial).-(cc_nonderived)";P(google[J].c,"RIGHTS_MODIFICATION",google[J].c.ee);google[J].c.ce="(cc_publicdomain|cc_attribute|cc_sharealike).-(cc_noncommercial|cc_nonderived)";P(google[J].c,"RIGHTS_COMMERCIAL_MODIFICATION",google[J].c.ce);
google[J].c.p=[];google[J].c.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].c.p[j];google[J].c.p[j]=f;a.aa(c,d,e,g)};P(google[J].c,"RawCompletion",google[J].c.N);
google[J].c[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].c.p,this):d;c=this.Ha(c==f?"google.search.ImageSearch.RawCompletion":c,d,e);if(a){a=a;if(this.L)a=a+" "+this.L;a="&q="+i(a);if(this.Aa)a=a+"&safe="+this.Aa;if(this.Pc)a=a+"&imgsz="+i(this.Pc);if(this.Nc)a=a+"&imgc="+i(this.Nc);if(this.Oc)a=a+"&imgcolor="+i(this.Oc);if(this.Qc)a=a+"&imgtype="+i(this.Qc);if(this.Jc)a=a+"&as_filetype="+i(this.Jc);if(this.Yc)a=a+"&as_rights="+i(this.Yc);if(this.m)a=a+"&as_sitesearch="+i(this.m);c+=a;
this.z=a;if(e&&e!=0)this.z=this.z+"&start="+e}return c};
google[J].c[F].I=function(a){a.html&&delete a.html;var c=W(this.va());Z(c,"gs-result");var d=W("gs-image-box"),e=google[J].a.gb(a.tbWidth,a.tbHeight,this.T),g=ob(a.tbUrl,e[x],e[Va],"gs-image");g[I].left=(this.T[x]-e[x])/2+"px";s(g,a.titleNoFormatting+" ("+a.visibleUrl+")");e=pb(a.unescapedUrl,f,this.v(),"gs-image");t(e,"gs-image");T(e,g);T(d,e);T(c,d);d=W("gs-text-box");g=U(a[va],"gs-snippet");s(g,a.contentNoFormatting);T(d,g);g=U(a[x]+" x "+a[Va],"gs-size");T(d,g);g=Y(a.originalContextUrl,a.visibleUrl,
this.v(),"gs-visibleUrl");s(g,a.visibleUrl);T(d,g);T(c,d);a.html=c;this.Da(a.html)};P(google[J].c[F],"createResultHtml",google[J].c[F].I);google[J].c[F].Ba=function(a){this.m=a};P(google[J].c[F],"setSiteRestriction",google[J].c[F].Ba);
google[J].c[F].X=function(a,c){if(a==google[J].a.kc)this.Aa=c?c==google[J].a.mc||c==google[J].a.lc?c:f:f;else if(a==google[J].c.$d)this.Pc=c?c[Wa]("|"):f;else if(a==google[J].c.Yd)this.Nc=c?c==google[J].c.kd||c==google[J].c.md||c==google[J].c.ld?c:f:f;else if(a==google[J].c.Xd)this.Oc=c?c==google[J].c.vd||c==google[J].c.sd||c==google[J].c.yd||c==google[J].c.rd||c==google[J].c.wd||c==google[J].c.od||c==google[J].c.ud||c==google[J].c.td||c==google[J].c.xd||c==google[J].c.qd||c==google[J].c.nd||c==google[J].c.pd?
c:f:f;else if(a==google[J].c.Zd)this.Jc=c?c==google[J].c.Dd||c==google[J].c.Ed||c==google[J].c.Cd||c==google[J].c.Bd?c:f:f;else if(a==google[J].c.ae)this.Qc=c?c==google[J].c.Gd||c==google[J].c.Fd||c==google[J].c.Hd||c==google[J].c.Id||c==google[J].c.Jd?c:f:f;else if(a==google[J].c.be)this.Yc=c?c==google[J].c.fe||c==google[J].c.de||c==google[J].c.ee||c==google[J].c.ce?c:f:f};P(google[J].c[F],"setRestriction",google[J].c[F].X);google[J].f=function(){google[J].a[K](this);this.ga=f;this.ea="San Francisco, CA";this.ka={y:37.77916,x:-122.42009};this.Xa=f;this.zb=b;this.mb=h;this.db=f;this.$a=b;this.la=eb(this,this.xa);this.Za="gsc-locationConfig";this.A="local";this.Ja="/GlocalSearch";this.wa="http://www.google.com/local";this.Wa=this.K=f};O("google.search.LocalSearch",google[J].f);Za(google[J].f,google[J].a);google[J].f.H="GlocalSearch";P(google[J].f,"RESULT_CLASS",google[J].f.H);google[J].f.re="blended";
P(google[J].f,"TYPE_BLENDED_RESULTS",google[J].f.re);google[J].f.ue="kmlonly";P(google[J].f,"TYPE_KMLONLY_RESULTS",google[J].f.ue);google[J].f.ve="localonly";P(google[J].f,"TYPE_LOCALONLY_RESULTS",google[J].f.ve);google[J].f.gd="disabled";P(google[J].f,"ADDRESS_LOOKUP_DISABLED",google[J].f.gd);google[J].f.hd="enabled";P(google[J].f,"ADDRESS_LOOKUP_ENABLED",google[J].f.hd);google[J].f.ke=0;P(google[J].f,"STATIC_MAP_ZOOM_FARTHEST",google[J].f.ke);google[J].f.dg=13;
P(google[J].f,"STATIC_MAP_ZOOM_DEFAULT",google[J].f.dg);google[J].f.je=21;P(google[J].f,"STATIC_MAP_ZOOM_CLOSEST",google[J].f.je);google[J].f.rc=8;P(google[J].f,"STATIC_MAP_MAX_POINTS",google[J].f.rc);google[J].f.dh=3.141592653589;google[J].f.xg=6367E3;google[J].f.Kh=16093;google[J].f.p=[];google[J].f.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].f.p[j];google[J].f.p[j]=f;a.resultViewport=c&&c.viewport?c.viewport:f;a.aa(c,d,e,g)};P(google[J].f,"RawCompletion",google[J].f.N);
google[J].f[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].f.p,this):d;c=this.Ha(c==f?"google.search.LocalSearch.RawCompletion":c,d,e);e="";if(a){e="&q="+i(a);c+=e}this.fj=f;if(this.ga){var g;if(this.zb){d=this.ga.getCenterLatLng();g=this.ga.getSpanLatLng();a="&sll="+d.y+","+d.x;a+="&sspn="+g[Va]+","+g[x]}else{d=this.ga.getCenter();g=this.ga.getBounds().toSpan().toUrlValue();a="&sll="+d.y+","+d.x;a+="&sspn="+g}a+=google[J].f.wc(d.y,d.x);c+=a;e+=a}else if(this.ka){a="&sll="+this.ka.y+","+
this.ka.x;if(this.Xa)a=a+"&sspn="+this.Xa.lat+","+this.Xa.lng;a+=google[J].f.wc(this.ka.y,this.ka.x);c+=a;e+=a}else if(this.ea){a="&near="+i(this.ea);c+=a;e+=a}if(this.mb){c+="&nogeocode=t";e+="&nogeocode=t"}if(this.db){c+="&mrt="+i(this.db);e+="&mrt="+i(this.db)}if(e)this.z=e;return c};google[J].f.wc=function(a,c){var d=2*google[J].f.Kh/google[J].f.xg*2*google[J].f.dh;return"&gll="+p[ua]((a-d)*1E6)+","+p[ua]((c-d)*1E6)+","+p[ua]((a+d)*1E6)+","+p[ua]((c+d)*1E6)+"&llsep=500,500"};
P(google[J].f,"centerToGll",google[J].f.wc);
google[J].f[F].I=function(a){a.html&&delete a.html;var c=W(this.va());Z(c,"gs-result");var d;d=Y(a.url,a[Ea],this.v(),"gs-title");T(c,d);if(a.listingType=="kml"&&a[va]&&a[va]!=""){d=U(a[va],"gs-snippet");T(c,d)}var e=W("gs-address");if(a.addressLines&&a.addressLines[E]>0)for(var g=0;g<a.addressLines[E];g++){d=a.addressLines[g];var j="gs-addressLine";if(g==0)j="gs-street gs-addressLine";else if(g==1)j="gs-city gs-addressLine";d=U(d,j);T(e,d)}else{d=U(a.streetAddress,"gs-street");T(e,d);g="";if(a.city!=
""){g=a.city;if(a.region!="")g+=", "}d=U(g,"gs-city");T(e,d);d=U(a.region,"gs-region");T(e,d)}d=U(a.country,"gs-country");T(e,d);T(c,e);if(a.phoneNumbers&&a.phoneNumbers[E]){g=e=f;d=a.phoneNumbers[0];for(var l=0;l<a.phoneNumbers[E];l++){j=a.phoneNumbers[l];if(j[Ba]=="main"){e=j;break}if(j[Ba]==""||j[Ba]=="mobile"&&g==f)g=j}j=e?e:g?g:d;d=U(j.number,"gs-phone");T(c,d)}if(a.ddUrl&&a.ddUrl!=""){d=Y(a.ddUrl,Q.directions,this.v(),"gs-directions");T(c,d)}if(a.ddUrlToHere&&a.ddUrlToHere!=""&&a.ddUrlFromHere&&
a.ddUrlFromHere!=""){d=W("gs-directions-to-from");e=U(Q["get-directions"]+":","gs-label");d[v](e);e=Y(a.ddUrlToHere,Q["to-here"],this.v(),"gs-secondary-link");d[v](e);e=U("-","gs-spacer");d[v](e);e=Y(a.ddUrlFromHere,Q["from-here"],this.v(),"gs-secondary-link");d[v](e);T(c,d)}a.html=c;this.Da(a.html)};P(google[J].f[F],"createResultHtml",google[J].f[F].I);
google[J].f[F].jf=function(a){if(a.centerAndZoom){this.zb=b;this.ga=a;this.ka=f;this.ea="";if(this.K)this.K=f}else if(a.setCenter){this.zb=h;this.ga=a;this.Xa=this.ka=f;this.ea="";if(this.K)this.K=f}else if(a.x&&a.y){this.zb=b;this.ka=a;this.ga=this.Xa=f;this.ea="";if(this.K)this.K=f}else if(a!=f&&a!=""){this.zb=b;this.ga=f;this.ea=a;this.ka=f;if(this.K)this.K=f;var c=new google[J].f;c.Jb(this,this.ig,[c,a]);c[M](a)}};P(google[J].f[F],"setCenterPoint",google[J].f[F].jf);
google[J].f[F].ig=function(a,c){if(a.results&&a.results[E]){var d={};d.y=da(a.results[0].lat);d.x=da(a.results[0].lng);this.ka=d;this.ea=c;this.$a=b;this.ga=f;if(a.resultViewport){d={};d.ti=da(a.resultViewport.span.lat)/2;d.ui=da(a.resultViewport.span.lng)/2;this.Xa=d}}};
google[J].f[F].xa=function(a,c){if(c){if(this.K==f){var d=f;if(this.ga==f){var e=W("gsc-configSetting");this.K=sb(f,"gsc-configSettingInput",this.ea==""?f:this.ea);T(e,U(Q["search-location"],"gsc-configSettingInputLabel"));T(e,this.K);T(a,e);d=this.K}e=W("gsc-configSetting");this.Wa=tb(f,"0",this.mb,"gsc-configSettingCheckbox");T(e,this.Wa);T(e,U(Q["disable-address-lookup"],"gsc-configSettingCheckboxLabel"));if(d==f)d=this.Wa;var g=U(f,"gsc-configSettingSubmit");T(g,rb(Q[Na],"gsc-configSettingSubmit"));
T(e,g);T(a,e);d[xa]()}}else{if(this.K){if(this.K[A]){this.ea=this.K[A];this.jf(this.ea)}this.K=f}if(this.Wa){this.mb=this.Wa[Ha];this.Wa=f}fb(a)}};google[J].f[F].oh=function(a){if(a==google[J].f.gd)this.mb=b;else if(a==google[J].f.hd)this.mb=h};P(google[J].f[F],"setAddressLookupMode",google[J].f[F].oh);google[J].f.ef=function(a,c,d,e){var g=a.staticMapUrl;g=g[y](/&size=\d*x\d*/,"&size="+d+"x"+c);if(e&&e<=google[J].f.je&&e>=google[J].f.ke)g=g[y](/&zoom=\d*/,"&zoom="+e);return a.staticMapUrl=g};
P(google[J].f,"resizeStaticMapUrl",google[J].f.ef);
google[J].f.rg=function(a,c,d,e){var g="",j="http://maps.google.com/maps/api/staticmap?maptype=roadmap&size=150x100&zoom=13&format=gif&sensor=false",l={};l.staticMapUrl=j;j=google[J].f.ef(l,c,d,e);if(e==f)j=j[y](/&zoom=\d*/,"");c=a[E];if(c>google[J].f.rc)c=google[J].f.rc;for(d=0;d<c;d++){l=a[d];if(l.lat&&l.lng)if(typeof l.lat=="string"){e=da(l.lat);l=da(l.lng)}else{e=l.lat;l=l.lng}else if(l.x&&l.y){e=l.y;l=l.x}else return f;e="&markers=__ICONID____LAT__,__LNG__"[y](/__LAT__/,e);e=e[y](/__LNG__/,l);
l=65+d;e=c>1?e[y](/__ICONID__/,"label:"+String.fromCharCode(l)+"|"):e[y](/__ICONID__/,"");g+=e}return j+g};P(google[J].f,"computeStaticMapUrl",google[J].f.rg);google[J].f[F].X=function(a,c){if(a==google[J].a.Nb)if(c){this.db=f;this.db=c==google[J].f.re||c==google[J].f.ue||c==google[J].f.ve?c:f}else this.db=f};P(google[J].f[F],"setRestriction",google[J].f[F].X);google[J].o=function(){google[J].a[K](this);this.A="news";this.Ja="/GnewsSearch";this.wa="http://news.google.com/nwshp";this.Si=f;this.hb="site:";this.U=h;this.$a=b;this.la=eb(this,this.xa);this.Za="gsc-newsConfig";this.B=this.q=f};O("google.search.NewsSearch",google[J].o);Za(google[J].o,google[J].a);google[J].o.H="GnewsSearch";P(google[J].o,"RESULT_CLASS",google[J].o.H);google[J].o.Vd="GnewsSearch.quote";P(google[J].o,"QUOTE_RESULT_CLASS",google[J].o.Vd);google[J].o.p=[];
google[J].o.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].o.p[j];google[J].o.p[j]=f;a.aa(c,d,e,g)};P(google[J].o,"RawCompletion",google[J].o.N);
google[J].o[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].o.p,this):d;c=this.Ha(c==f?"google.search.NewsSearch.RawCompletion":c,d,e);if(a||!a&&this.B){d=f;if(a)d=a;if(this.L)d=d==f?this.L:d+" "+this.L;if(this.m)d=d==f?this.hb+this.m:d+" "+this.hb+this.m;a=d?"&q="+i(d):"";if(this.U)a+="&scoring=d";if(this.B){d="";for(var g in this.B)if(g.charAt(0)==":")d+="&"+this.B[g];a+=d}if(this.m&&this.hb=="source:")c=c[y](/&hl=.*&/,"&hl=en&");c+=a;this.z=a;if(e&&e!=0)this.z=this.z+"&start="+e}return c};
google[J].o[F].I=function(a){a.html&&delete a.html;if(a.GsearchResultClass!=google[J].o.Vd){var c=W(this.va());Z(c,"gs-result");var d;d=Y(a.unescapedUrl,a[Ea],this.v(),"gs-title");T(c,d);d=U(a.publisher,"gs-publisher");T(c,d);d=a[La][Ja](",");if(d[E]>1){d=U(", "+d[d[E]-1],"gs-location");T(c,d)}d=new Date(a.publishedDate);d=U(" - "+this.bb(d),"gs-publishedDate");T(c,d);d=new Date(a.publishedDate);d=U(" - "+this.Kc(d),"gs-relativePublishedDate");T(c,d);d=U(a[va],"gs-snippet");T(c,d);if(a.clusterUrl&&
a.clusterUrl!=""){d=Y(a.clusterUrl,Q["related-articles"]+"&nbsp;&raquo;",this.v(),"gs-clusterUrl");T(c,d)}a.html=c;this.Da(a.html)}};P(google[J].o[F],"createResultHtml",google[J].o[F].I);google[J].o[F].Ba=function(a){if(a==f||a==""){this.m=f;this.hb="site:"}else if(a[C]("[./:]")){this.hb="site:";this.m=a}else{this.hb="source:";this.m=a[y](/\s/g,"_")}};P(google[J].o[F],"setSiteRestriction",google[J].o[F].Ba);google[J].o[F].P=function(a){this.U=a==google[J].a.ua?b:h};
P(google[J].o[F],"setResultOrder",google[J].o[F].P);google[J].o[F].xa=function(a,c){if(c){if(this.q==f){var d=W("gsc-configSetting");this.q=tb(f,"0",this.U,"gsc-configSettingCheckbox");T(d,this.q);T(d,U(Q["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,rb(Q[Na],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.q,this.U);this.q[xa]()}else if(this.q)this.q[Ha]?this.P(google[J].a.ua):this.P(google[J].a.lb)};
google[J].o[F].lg={geo:b,qsid:b,quotesearch:b,topic:b,ned:b,scoring:b,as_mind:b,as_minm:b,as_miny:b,as_maxd:b,as_maxm:b,as_maxy:b};google[J].o[F].X=function(a,c){if(a==google[J].a.Ua)if(c)for(var d in c){var e=c[d];if(typeof this.lg[d]!="undefined"){this.B=this.B||{};this.B[":"+d]=d+"="+i(e)}}else this.B=f};P(google[J].o[F],"setRestriction",google[J].o[F].X);google[J].j=function(){google[J].a[K](this);this.A="patent";this.Ja="/GpatentSearch";this.wa="http://www.google.com/patents";this.pf="";this.Eb=f;this.$a=b;this.la=eb(this,this.xa);this.Za="gsc-patentConfig";this.q=f};O("google.search.PatentSearch",google[J].j);Za(google[J].j,google[J].a);google[J].j.H="GpatentSearch";P(google[J].j,"RESULT_CLASS",google[J].j.H);google[J].j.pe=1;P(google[J].j,"TYPE_ANY_STATUS",google[J].j.pe);google[J].j.te=2;P(google[J].j,"TYPE_ISSUED_PATENTS",google[J].j.te);
google[J].j.qe=3;P(google[J].j,"TYPE_APPLICATIONS",google[J].j.qe);google[J].j.p=[];google[J].j.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].j.p[j];google[J].j.p[j]=f;a.aa(c,d,e,g)};P(google[J].j,"RawCompletion",google[J].j.N);google[J].j[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].j.p,this):d;c=this.Ha(c==f?"google.search.PatentSearch.RawCompletion":c,d,e);if(a){a=a;if(this.L)a=a+" "+this.L;a="&q="+i(a)+this.pf;if(this.Eb)a+=this.Eb;c+=a;this.z=a}return c};
google[J].j[F].I=function(a){a.html&&delete a.html;a.thumbnailHtml=this.Dc(a);var c=W(this.va());Z(c,"gs-result");var d=W("gs-text-box"),e=lb(),g=mb(e,0),j=X(g,"gs-image-box");g=X(g,"gs-text-box");T(j,a.thumbnailHtml[Aa](b));T(g,d);T(c,e);j=Y(a.unescapedUrl,a[Ea],this.v(),"gs-title");T(d,j);e=W("gs-patent-info gs-metadata");T(d,e);j=f;j=a.patentNumber?a.patentStatus=="issued"?Q["us-pat"]+"&nbsp;"+a.patentNumber:Q["us-pat-app"]+"&nbsp;"+a.patentNumber:Q["us-pat-app"]+"&nbsp; N/A";j=U(j,"gs-patent-number");
T(e,j);if(a.applicationDate){j=U(" - "+this.bb(new Date(a.applicationDate)),"gs-publishedDate");T(e,j)}if(a.assignee){j=U(" - "+a.assignee,"gs-author");T(e,j)}j=U(a[va],"gs-snippet");T(d,j);T(d,j);a.html=c;this.Da(a.html)};P(google[J].j[F],"createResultHtml",google[J].j[F].I);google[J].j[F].Dc=function(a){var c=W("gs-patent-image"),d=ob(a.tbUrl,75,100,"gs-image");a=pb(a.unescapedUrl,f,this.v(),"gs-image");t(a,"gs-image");T(a,d);T(c,a);return c};
google[J].j[F].P=function(a){this.Eb=a==google[J].a.ua?"&scoring=d":a==google[J].a.Ud?"&scoring=ad":f};P(google[J].j[F],"setResultOrder",google[J].j[F].P);google[J].j[F].X=function(a,c){if(a==google[J].a.Nb)this.pf=c?c==google[J].j.pe?"":c==google[J].j.te?"&as_psrg=1":c==google[J].j.qe?"&as_psra=1":"":""};P(google[J].j[F],"setRestriction",google[J].j[F].X);
google[J].j[F].xa=function(a,c){if(c){var d=h;if(this.Eb&&this.Eb=="&scoring=d")d=b;if(this.q==f){var e=W("gsc-configSetting");this.q=tb(f,"0",d,"gsc-configSettingCheckbox");T(e,this.q);T(e,U(Q["sort-by-date"],"gsc-configSettingCheckboxLabel"));d=W("gsc-configSettingSubmit");T(d,rb(Q[Na],"gsc-configSettingSubmit"));T(e,d);T(a,e)}else ka(this.q,d);this.q[xa]()}else if(this.q)this.q[Ha]?this.P(google[J].a.ua):this.P(google[J].a.lb)};google[J].D=function(){this.bf=this.da=google[J].b.La;this.k=f;this.T={width:112,height:84};this.ic={width:100,height:75};this.Ab=f};O("google.search.SearcherOptions",google[J].D);google[J].D[F].lf=function(a){switch(a){case google[J].b.Ad:case google[J].b.Sa:case google[J].b.La:this.da=a;break;default:this.da=google[J].b.La}this.bf=this.da};P(google[J].D[F],"setExpandMode",google[J].D[F].lf);google[J].D[F].yh=function(a){fb(a);this.k=a};P(google[J].D[F],"setRoot",google[J].D[F].yh);
google[J].D[F].Ib=function(a){this.Ab=a};P(google[J].D[F],"setNoResultsString",google[J].D[F].Ib);google[J].D[F].sh=function(a){if(a>100)a=100;pa(this.T,a);ha(this.T,p[ta](a*1.33))};P(google[J].D[F],"setImageResultsTbHeight",google[J].D[F].sh);google[J].D[F].Eh=function(a){if(a>100)a=100;pa(this.ic,a);ha(this.ic,p[ta](a*1.33))};P(google[J].D[F],"setVideoResultsTbHeight",google[J].D[F].Eh);google[J].M=function(){ga(this,f);this.of=f;this.S=google[J].b.Ca;this.Fe=h};O("google.search.DrawOptions",google[J].M);
google[J].M[F].th=function(a){ga(this,a)};P(google[J].M[F],"setInput",google[J].M[F].th);google[J].M[F].zh=function(a){if(a&&typeof a=="string")a=o[z](a);this.of=a};P(google[J].M[F],"setSearchFormRoot",google[J].M[F].zh);google[J].M[F].kf=function(a){this.S=a==google[J].b.Ca||a==google[J].b.ra?a:google[J].b.Ca};P(google[J].M[F],"setDrawMode",google[J].M[F].kf);google[J].M[F].qh=function(a){this.Fe=a};P(google[J].M[F],"setAutoComplete",google[J].M[F].qh);
google[J].C=function(a,c,d){this.w=d;this.Bc=this.Ic=h;this.h=a;this.G=f;this.kh=S(c,google[J].b[F].bh,[this]);this.nh=S(c,google[J].b[F].Uc,[this,google[J].C.qc]);this.mh=S(c,google[J].b[F].Uc,[this,google[J].C.pc]);this.lh=S(c,google[J].b[F].Uc,[this,google[J].C.ie]);this.jh=S(c,google[J].b[F].ah,[this]);this.ih=S(c,google[J].b[F].Wg,[this]);this.h.Jb(c,google[J].b[F].aa,[this]);this.h.Y(c.Db);this.h.Hb(c.Oa);this.W=this.ab=this.Fa=this.Xc=this.vb=this.gc=this.k=f;this.yb=b};google[J].C.oc=0;
google[J].C.qc=1;google[J].C.pc=2;google[J].C.ie=3;google[J].C[F].ad=function(a){var c="gsc-results-selector ";c+=a==google[J].C.oc?this.w.da==google[J].b.La?"gsc-one-result-active":this.h.za==google[J].a.ia?"gsc-more-results-active":"gsc-all-results-active":a==google[J].C.qc?"gsc-one-result-active":a==google[J].C.pc?"gsc-more-results-active":"gsc-all-results-active";t(this.Xc,c)};
google[J].b=function(a){if(!google[L].KeyVerified)if(google[J].b.Xe())google[L].KeyVerified=b;else return;this.Ce=this.Db=google[J].a.ia;this.S=google[J].b.Ca;this.$b=this.k=f;ga(this,f);this.fc=google[J].b.Ob;this.Og=S(this,google[J].b[F].Xg,[f]);this.Pg=S(this,google[J].b[F].Yg,[f]);this.cb=this.Fb=this.Zc=this.Wb=f;this.nb=this.Sg=h;this.Oa=google[J].a.kb;this.Rc=Q.copy;this.e=[];this.Uh=[];var c;if(a)for(var d=0;d<a[E];d++){c=new google[J].C(a[d],this,h);this.e[qa](c)}};
O("google.search.SearchControl",google[J].b);google[J].b[F].Vc=h;google[J].b.Td=Q["no-results"];P(google[J].b,"NO_RESULTS_DEFAULT_STRING",google[J].b.Td);google[J].b.ne=350;P(google[J].b,"TIMEOUT_SHORT",google[J].b.ne);google[J].b.Ob=500;P(google[J].b,"TIMEOUT_MEDIUM",google[J].b.Ob);google[J].b.me=700;P(google[J].b,"TIMEOUT_LONG",google[J].b.me);google[J].b.Ad=1;P(google[J].b,"EXPAND_MODE_CLOSED",google[J].b.Ad);google[J].b.Sa=2;P(google[J].b,"EXPAND_MODE_OPEN",google[J].b.Sa);google[J].b.La=3;
P(google[J].b,"EXPAND_MODE_PARTIAL",google[J].b.La);google[J].b.Ca=1;P(google[J].b,"DRAW_MODE_LINEAR",google[J].b.Ca);google[J].b.ra=2;P(google[J].b,"DRAW_MODE_TABBED",google[J].b.ra);google[J].b.Qd="save";P(google[J].b,"KEEP_LABEL_SAVE",google[J].b.Qd);google[J].b.Pd="keep";P(google[J].b,"KEEP_LABEL_KEEP",google[J].b.Pd);google[J].b.Od="include";P(google[J].b,"KEEP_LABEL_INCLUDE",google[J].b.Od);google[J].b.Nd="copy";P(google[J].b,"KEEP_LABEL_COPY",google[J].b.Nd);google[J].b.Md="blank";
P(google[J].b,"KEEP_LABEL_BLANK",google[J].b.Md);var Hb=google[L][Ra].BUBBLEGUM,Ib=google[L][Ra].GREENSKY,Jb=google[L][Ra].ESPRESSO,Kb=google[L][Ra].SHINY,Lb=google[L][Ra].MINIMALIST;google[J].b.Ka={};google[J].b.Ka[Hb]={colorBackground:"#FDE5FF",colorTitleLink:"#0568CD",colorText:"#000",colorDomainLink:"#CC7A9F",fontFamily:"Arial"};
google[J].b.Ka[Ib]={colorBackground:"#EEFFE5",colorBorder:"#A9DA92",colorTitleLink:"#06C",colorText:"#454545",colorDomainLink:"#8D5FA7",fontFamily:"Trebuchet MS",fontSizeTitle:"14",fontSizeDescription:"14"};google[J].b.Ka[Jb]={colorBackground:"#F2F0E6",colorTitleLink:"#950000",colorText:"#333",colorDomainLink:"#A25B08",fontFamily:"Georgia",fontSizeTitle:"14",fontSizeDescription:"14",fontSizeDomainLink:"11"};
google[J].b.Ka[Kb]={colorBackground:"#F0F0F6",colorBorder:"#CCC",colorTitleLink:"#06C",colorDomainLink:"#008000",fontFamily:"Verdana"};google[J].b.Ka[Lb]={colorBackground:"#EEE",colorBorder:"#CCC",colorTitleLink:"#000",colorText:"#444",colorDomainLink:"#333",fontFamily:"Arial"};google[J].b.jc="gsc-loading-id";try{google[J].b.appPath=m[La].href}catch(Nb){google[J].b.appPath=f}
google[J].b.Xe=function(){var a=b,c;c=m[La].host[Xa]()[Ja](".");if(c[E]<2)c=h;else{var d=c.pop(),e=c.pop();if((e=="igoogle"||e=="gmodules"||e=="googlesyndication")&&d=="com")c=b;else{if(d[E]==2&&c[E]>0)if(vb[e]&&vb[e][d]==1)e=c.pop();c=e=="google"}}if(c)return b;if(google[L].LoadFailure)if(google[L].OriginalAppPath&&google[J].b.appPath){google[L].LoadFailure=h;a=b}google[L].KeyVerified=b;google[L].LoadFailure=h;return a};P(google[J].b,"keyCheck",google[J].b.Xe);
google[J].b[F].kg=function(){var a=this;return function(){if(a.Vc){a.df();a.Vc=h}}};
google[J].b[F].qb=function(a,c){google.load("ads.search","2",{callback:this.kg()});this.Ea=b;this.Ma=a;if(c){if(c.includeVerticalAds!=n)this.pa=c.includeVerticalAds;if(c.includeSideAds!=n)this.pa=c.includeSideAds;if(c.iframes!=n)this.tb=c.iframes;if(c.useNarrowTopAd!=n)if(this.tb)this.$i=c.useNarrowTopAd;if(c.channel)this.ze=c.channel;if(c.clientIP)this.Ae=c.clientIP;if(c.safe)this.tc=c.safe;if(c.userAgent)this.De=c.userAgent;var d=c.adtest||c.debug;if(d)this.uc=d;if(c.numTopAds!=n){this.na=c.numTopAds;
this.na=p.max(0,p.min(4,this.na))}if(c.numSideAds!=n){this.fa=c.numSideAds;this.pa=(this.fa=p.max(0,p.min(8,this.fa)))?b:h}this.hf=c.enableSearchCompleteCallback?b:h}};P(google[J].b[F],"enableAds",google[J].b[F].qb);google[J].b[F].Va=function(a,c){c||(c=new google[J].D);a.ya=f;this.e[qa](new google[J].C(a,this,c));if(this.ac(a))this.Lg=b;a.bc="gsc"};P(google[J].b[F],"addSearcher",google[J].b[F].Va);
google[J].b[F].Me=function(a){if(this.e[a].w.k){this.e[a].yb=h;this.e[a].k=this.e[a].w.k;Z(this.e[a].k,"gsc-resultsRoot");$(this.e[a].k,"gsc-resultsbox-visible");Z(this.e[a].k,"gsc-resultsbox-invisible")}else this.e[a].k=W("gsc-resultsRoot");this.e[a].h.Mb&&Z(this.e[a].k,"gsc-resultsRoot-"+this.e[a].h.Mb);if(this.S==google[J].b.ra)this.l[a].J=this.e[a].k;var c=lb(f,f,"gsc-resultsHeader"),d=mb(c,0);this.e[a].Ra=X(d,"gsc-twiddleRegionCell");d=X(d,"gsc-configLabelCell");this.e[a].gc=U("","gsc-twiddle");
T(this.e[a].Ra,this.e[a].gc);var e=ib(this.e[a].h.Hg(),"gsc-title");T(this.e[a].gc,e);this.e[a].vb=U("","gsc-stats");T(this.e[a].Ra,this.e[a].vb);e=U();var g=U(Q.blank,"gsc-result-selector gsc-one-result"),j=U(Q.blank,"gsc-result-selector gsc-more-results"),l=U(Q.blank,"gsc-result-selector gsc-all-results");s(g,Q["show-one-result"]);s(j,Q["show-more-results"]);s(l,Q["show-all-results"]);T(e,g);T(e,j);T(e,l);ma(g,this.e[a].nh);ma(j,this.e[a].mh);ma(l,this.e[a].lh);this.e[a].Xc=e;this.e[a].ad(google[J].C.oc);
T(this.e[a].Ra,this.e[a].Xc);ma(this.e[a].gc,this.e[a].kh);if(this.e[a].h.la){this.e[a].V=kb("","gsc-configLabel");q(this.e[a].V,Q.blank);Z(this.e[a].V,"gsc-twiddle-closed");T(d,this.e[a].V);ma(this.e[a].V,this.e[a].jh);s(this.e[a].V,Q.settings);this.e[a].Fa=W("gsc-config");Z(this.e[a].Fa,this.e[a].h.Za);this.e[a].ab=qb("gsc-config");Z(this.e[a].ab,this.e[a].h.Za);this.e[a].ab.onsubmit=this.e[a].ih;T(this.e[a].Fa,this.e[a].ab);na(this.e[a].Fa[I],"none")}this.e[a].W=W("gsc-results");d=this.e[a].h.Mc();
Z(this.e[a].W,d);this.e[a].w.k==f&&T(this.Ia,this.e[a].k);T(this.e[a].k,c);this.e[a].Fa&&T(this.e[a].k,this.e[a].Fa);T(this.e[a].k,this.e[a].W)};google[J].b[F].Ne=function(a){var c=this.e[a],d={},e=c.h.Kg();d.$=ib(e);d.J=f;d.$c=c.h;d.A=c.h.A;ma(d.$,S(this,this.Jh,[a]));this.l[a]=d;T(this.ha,d.$);a="gs-spacer";if(ab("opera"))a+=" gs-spacer-opera";a=kb(" ",a);T(this.ha,a);c.w.lf(google[J].b.Sa)};
google[J].b[F].Tb=function(a,c){var d=f,e=f;if(c)if(c.S){this.S=c.S;d=c[w];e=c.of}else this.S=google[J].b.Ca;else this.S=google[J].b.Ca;this.k=W("gsc-control");if(d!=f){ga(this,d);this[w].onkeyup=this.Og;this[w].onpaste=this.Pg}else{if(e==f)e=this.k;d=new google[J].Q(b,e);d.nf(this,this[sa]);d.mf(this,this.xc);ga(this,d[w]);this.rb&&d.Mg()}this.Ia=W("gsc-resultsbox-invisible");if(this.S==google[J].b.ra){this.ha=W("gsc-tabsAreaInvisible");T(this.k,this.ha);this.l=[];for(d=this.u=0;d<this.e[E];d++)this.Ne(d)}this.ba=
this.k;if(this.Ea){this.ba=W("gsc-wrapper");this.R=W("gsc-adBlockInvisible");this.O=W("gsc-adBlockInvisible");T(this.ba,this.R);T(this.k,this.O);T(this.k,this.ba)}T(this.ba,this.Ia);for(d=0;d<this.e[E];d++){this.Me(d);if(this.S==google[J].b.ra){Z(this.l[d].$,"gsc-tabHeader");Z(this.l[d].J,"gsc-tabData");if(d==this.u){Z(this.l[d].$,"gsc-tabhActive");Z(this.l[d].J,"gsc-tabdActive")}else{Z(this.l[d].$,"gsc-tabhInactive");Z(this.l[d].J,"gsc-tabdInactive")}}}if(a&&typeof a=="string")a=o[z](a);if(a){gb(a,
this.k);if((d=this.Dg())&&d<300){this.Sg=b;Z(this.k,"gsc-narrow")}}};P(google[J].b[F],"draw",google[J].b[F].Tb);google[J].b[F].Ch=function(a){switch(a){case google[J].b.ne:case google[J].b.Ob:case google[J].b.me:this.fc=a;break;default:this.fc=google[J].b.Ob}};P(google[J].b[F],"setTimeoutInterval",google[J].b[F].Ch);
google[J].b[F].wh=function(a,c,d){if(d)switch(d){case google[J].b.Qd:case google[J].b.Pd:case google[J].b.Od:case google[J].b.Nd:case google[J].b.Md:this.Rc=Q[d];break;default:this.Rc=d}this.Wb=eb(a,c)};P(google[J].b[F],"setOnKeepCallback",google[J].b[F].wh);N=google[J].b[F];N.ac=function(a){var c=a.A;if(this.rb){if(c=="web"&&a.F!=google[J].g.Z)return h;return b}else return c=="blog"||c=="image"?b:h};
N.Jh=function(a){if(this.u!=a){$(this.l[this.u].$,"gsc-tabhActive");$(this.l[this.u].J,"gsc-tabdActive");Z(this.l[this.u].$,"gsc-tabhInactive");Z(this.l[this.u].J,"gsc-tabdInactive");this.u=a;a=this.l[this.u].$c;Z(this.l[this.u].$,"gsc-tabhActive");$(this.l[this.u].$,"gsc-tabhInactive");if(this.Ea)this.ac(a)?this.wb():this.Gc();if(this.Sc&&a.Ye==this.Sc){Z(this.l[this.u].J,"gsc-tabdActive");$(this.l[this.u].J,"gsc-tabdInactive")}else{var c=o[z](google[J].b.jc);if(!c){c=o[D]("div");c.id=google[J].b.jc;
c[v](o.createTextNode("Loading..."));this.l[this.u].J[Ta].insertBefore(c,this.l[this.u].J)}this.Hc(a,this.l[this.u].J,this.Sc)}}};N.wb=function(){if(this.Ea){t(this.R,"gsc-adBlockInvisible");t(this.O,"gsc-adBlockInvisible");this.pa&&$(this.ba,"gsc-thinWrapper")}};N.Gc=function(){if(this.Ea){t(this.R,this.fb&&this.fb>0?"gsc-adBlock":"gsc-adBlockInvisible");if(this.eb&&this.eb>0){t(this.O,"gsc-adBlockVertical");Z(this.ba,"gsc-thinWrapper")}else{t(this.O,"gsc-adBlockInvisible");$(this.ba,"gsc-thinWrapper")}}};
N.submit=function(){this[w][A][E]?this[M]():this.xc();return h};P(google[J].b[F],"submit",google[J].b[F][sa]);google[J].b[F].Sb=function(){if(this.ha&&!this.Ih&&(!this.rb||this.e[E]>1))t(this.ha,"gsc-tabsArea")};google[J].b[F].Be=function(a){var c=this;return function(d,e){if(e){if(a)c.fb=1;else c.eb=1;if(c.fb>0&&(c.pa&&c.eb>1||!c.pa)){m[ra](c.wg);c.Gc()}else c.wg=m[Ia](function(){c.Gc()},200)}}};
oa(google[J].b[F],function(a){if(a){a=a;this[w].onfocus&&this[w].onfocus();ia(this[w],a)}else a=this[w][A];if(a[E]){this.nb=h;t(this.Ia,"gsc-resultsbox-visible");this.Sb();this.ub=google[L].createGuidArg_();var c=this.Ea;if(c&&this.Lg&&this.S==google[J].b.Ca)c=h;var d=this.Rg(),e=this.Qg();if(d==n&&!this.Ma&&!this.tb)c=h;if(c){this.ph();c="w"+this.na;if(this.pa)c=c+"n"+this.fa;var g;if(this.tb){this.Ia[I].visibility="hidden";this.wb();q(this.R,"");q(this.O,"");this.ca={};this.ca.pubId=this.Ma||"google-coop";
this.ca.gcsc=b;if(d)this.ca.cx=d;else if(e)this.ca.cref=e;this.ca.hl=google[J][Ua]?i(google[J][Ua]):f;this.ca.adtest=this.uc?"on":f;this.ca.adsafe=this.tc||f;this.ca.query=a;if((e=google[J].a.Ig())&&e in google[J].b.Ka){e=google[J].b.Ka[e];for(var j in e)this.ca[j]=e[j]}if(google&&google.ads&&google.ads[J]&&google.ads[J].Ads)this.df();else this.Vc=b}else g="http://www.google.com/"+(d?"cse":"search")+"?output=js&num=0&ie=utf8&oe=utf8&q="+i(a)+"&hl="+i(google[J][Ua])+"&ad="+i(c)+"&js=uds&"+this.ub;
if(d)g+="&cx="+d;if(this.Ma)g+="&client="+i(this.Ma);if(this.ze)g+="&channel="+i(this.ze);if(this.uc)g+="&adtest=on";if(this.Ae)g+="&ip="+i(this.Ae);if(this.tc)g+="&adsafe="+i(this.tc);if(this.De)g+="&useragent="+i(this.De);if(!this.tb){var l=this;m.google_afs_request_done=function(r){l.Ug(r)};db(g)}}this.Sc=a;if(this.S==google[J].b.ra)this.Hc(this.l[this.u].$c,this.l[this.u].J,a);else for(g=0;g<this.e[E];g++)this.Hc(this.e[g].h,this.e[g].k,a)}});P(google[J].b[F],"execute",google[J].b[F][M]);N=google[J].b[F];
N.df=function(){this.eb=this.fb=0;if(this.na&&this.na>0){this.vf={container:this.R,number:this.na,callback:this.Be(b),lines:2};t(this.R,"gsc-adBlockNoHeight");pa(this.R[I],"0px")}if(this.pa&&this.fa&&this.fa>0){this.Fh={container:this.O,number:this.fa,callback:this.Be(h)};t(this.O,"gsc-adBlockVertical");Z(this.O,"gsc-adBlockNoHeight");Z(this.ba,"gsc-thinWrapper");pa(this.O[I],"0px")}if(this.na&&this.na>0)if(this.pa&&this.fa&&this.fa>0)new google.ads[J].Ads(this.ca,this.vf,this.Fh);else new google.ads[J].Ads(this.ca,
this.vf)};N.Hc=function(a,c,d){if(!a.yb&&this.S!=google[J].b.ra){$(c,"gsc-resultsbox-invisible");Z(c,"gsc-resultsbox-visible")}this.Zc&&this.Zc(this,a,d);if(a.ya)a.ya=f;a.ub=this.ub;a[M](d)};N.Rg=function(){for(var a=0;a<this.e[E];a++){var c=this.e[a].h;if(c.A=="web")if(c.F!=google[J].g.Z)if(c.F==google[J].g.pb)return c.m}return f};N.Qg=function(){for(var a=0;a<this.e[E];a++){var c=this.e[a].h;if(c.A=="web")if(c.F!=google[J].g.Z)if(c.F==google[J].g.ei)return c.m}return f};
N.Ug=function(a){m.google_afs_request_done=f;if(this.R){q(this.R,"");q(this.O,"");this.fb=this.eb=0;if(!a||a[E]<1)this.wb();else{if(!this.ha)for(var c=0;c<this.e[E];c++){var d=this.e[c].h;if(this.ac(d)){this.wb();return}}t(this.R,"gsc-adBlock");d=h;var e=o[D]("h2");c="";if(this.uc)c="*DEBUG* ";c+=Q["ads-by-google"];q(e,c);T(this.R,e);var g=a[E];for(c=0;c<g;c++){var j=a[c];if(j[Ba]=="text/wide"){this.fb++;var l=W("gsc-ad"),r=Y(j.url,j.line1,google[J].a.kb);T(l,r);r=o[D]("cite");q(r,j.visible_url);
T(l,r);r=kb();q(r,j.line2);T(l,r);T(this.R,l)}else if(this.pa){this.eb++;if(!d){d=b;Z(this.ba,"gsc-thinWrapper");T(this.O,e[Aa](b));t(this.O,"gsc-adBlockVertical")}l=W("gsc-ad");r=Y(j.url,j.line1,google[J].a.kb);T(l,r);r=kb();q(r,j.line2+"<br/>"+j.line3);T(l,r);r=o[D]("cite");q(r,j.visible_url);T(l,r);T(this.O,l)}}this.pa&&!d&&$(this.ba,"gsc-thinWrapper");if(this.ha){d=this.l[this.u].$c;this.ac(d)&&this.wb()}this.Fb&&this.hf&&this.Fb(this,"ads")}}};
N.Xg=function(){var a=this[w][A];if(a&&a!=""){this.cb&&m[ra](this.cb);this.cb=m[Ia](S(this,google[J].b[F][M],[f]),this.fc)}};N.Yg=function(){this.cb&&m[ra](this.cb);this.cb=m[Ia](S(this,google[J].b[F][M],[f]),this.fc)};N.ph=function(){var a,c;switch(this.Ce){case google[J].a.Ta:a=3;c=5;break;case google[J].a.ta:a=2;c=4;break;default:a=1;c=2}if(this.na==n)this.na=a;if(this.fa==n)this.fa=c};
N.Y=function(a){if(a>0&&a<=8)this.Db=a;else switch(a){case google[J].a.ta:case google[J].a.Ta:this.Db=google[J].a.ta;break;default:case google[J].a.ia:this.Db=google[J].a.ia}for(var c=0;c<this.e[E];c++)this.e[c].h.Y(a);this.Ce=a};P(google[J].b[F],"setResultSetSize",google[J].b[F].Y);google[J].b[F].Hb=function(a){this.Oa=a;for(var c=0;c<this.e[E];c++)this.e[c].h.Hb(a)};P(google[J].b[F],"setLinkTarget",google[J].b[F].Hb);google[J].b[F].Ib=function(a){for(var c=0;c<this.e[E];c++)this.e[c].w.Ib(a)};
P(google[J].b[F],"setNoResultsString",google[J].b[F].Ib);N=google[J].b[F];N.bh=function(a){a.Ic?this.Qa(a,h):this.Qa(a,b)};N.Qa=function(a,c,d){if(c){$(a.Ra,"gsc-twiddle-closed");Z(a.Ra,"gsc-twiddle-opened");a.Ic=b;na(a.W[I],"block")}else{$(a.Ra,"gsc-twiddle-opened");Z(a.Ra,"gsc-twiddle-closed");a.Ic=h;na(a.W[I],"none");q(a.vb,d?"(0)":"("+a.h.results[E]+")")}};N.Wg=function(a){this.Kb(a,h,b);return h};N.ah=function(a){if(a.h.$a)a.Bc?this.Kb(a,h,b):this.Kb(a,b,b)};
N.Kb=function(a,c,d){if(c){if(a.V&&a.h.la){Z(a.V,"gsc-twiddle-opened");$(a.V,"gsc-twiddle-closed");q(a.V,Q[Na]);a.Bc=b;na(a.Fa[I],"block");a.h.la(a.ab,b)}}else if(a.V&&a.h.la){$(a.V,"gsc-twiddle-opened");Z(a.V,"gsc-twiddle-closed");q(a.V,Q.blank);a.Bc=h;a.h.la(a.ab,h);na(a.Fa[I],"none");d&&this[M]()}};N.Zg=function(a,c){if(this.Wb){c.h.Ng();this.Wb(a)}};N.mg=function(){this.nb=b};P(google[J].b[F],"cancelSearch",google[J].b[F].mg);
google[J].b[F].xc=function(){ia(this[w],"");this[w].onblur&&this[w].onblur();t(this.Ia,"gsc-resultsbox-invisible");if(this.ha)t(this.ha,"gsc-tabsAreaInvisible");if(this.R)t(this.R,"gsc-adBlockInvisible");if(this.O){t(this.O,"gsc-adBlockInvisible");$(this.ba,"gsc-thinWrapper")}for(var a=0;a<this.e[E];a++){if(!this.e[a].yb){$(this.e[a].k,"gsc-resultsbox-visible");Z(this.e[a].k,"gsc-resultsbox-invisible")}var c=this.e[a];fb(c.W);c.G=f;this.Qa(c,h,b);this.Kb(c,h,h)}};
P(google[J].b[F],"clearAllResults",google[J].b[F].xc);
google[J].b[F].aa=function(a){if(this.tb&&a==this.e[this.u])this.Ia[I].visibility="visible";if(this.l&&this.l[this.u]&&this.l[this.u].J){Z(this.l[this.u].J,"gsc-tabdActive");$(this.l[this.u].J,"gsc-tabdInactive")}var c=o[z](google[J].b.jc);c&&c[Ta][Pa](c);var d,e=h,g;if(!this.nb){fb(a.W);a.G=f;this.Qa(a,h,b);this.Kb(a,h,h);a.ad(google[J].C.oc);var j=a.h.context,l=this.ha&&j;if(this.rb&&!this.hg){if(l){g=j[Ea];for(c=0;c<this.l[E];c++){d=this.l[c];if(d.A==a.h.A){var r=a.h;g&&!a.h.ib&&gb(d.$,hb(g));
break}}}this.hg=b;this.Sb()}if((d=a.h.promotions)&&d[E]>0)for(c=0;c<d[E];c++){var u=d[c];u.html||a.h.Le(u);if(u.html){g=W(a.h.Mc());Z(g,"gsc-result");var B=u.html[Aa](b);T(g,B);T(a.W,g)}}u=a.h.results;if(a.h.sb&&a.h.completionStatus>=400){u=[];u[qa](a.h.Ag())}else if(u[E]==0&&a.w.Ab&&a.h.completionStatus==200){u=[];u[qa](a.h.Bg(a.w.Ab))}for(c=0;c<u[E];c++){d=u[c];d.html||a.h.I(d);if(d.html){e=b;g=W(a.h.Mc());Z(g,"gsc-result");a.h.Mb&&Z(g,"gsc-result-"+a.h.Mb);B=d.html[Aa](b);if(d.GsearchResultClass==
google[J].c.H){if(a.w.T)if(a.w.T[x]!=a.h.T[x]||a.w.T[Va]!=a.h.T[Va])for(var G=B.getElementsByTagName("img"),V=0;V<G[E];V++)google[J].a.gb(d.tbWidth,d.tbHeight,a.w.T,G[V],b)}else if(d.GsearchResultClass==google[J].t.H)if(a.w.ic){G=B.getElementsByTagName("img");for(V=0;V<G[E];V++)google[J].a.gb(d.tbWidth,d.tbHeight,a.w.ic,G[V])}T(g,B);if(this.Wb){B=this.Rc;G=U("","gsc-keeper");q(G,B);T(g,G);ma(G,S(this,google[J].b[F].Zg,[d,a]))}if(c>=a.h.af){if(!a.G){a.G=W("gsc-expansionArea");T(a.W,a.G);if(a.w.da==
google[J].b.La)na(a.G[I],"none")}T(a.G,g)}else T(a.W,g)}}if(!a.G&&a.h[H]){a.G=W("gsc-expansionArea");T(a.W,a.G)}if(a.G&&a.h.z&&a.h.gwsUrl&&a.h[H]){c=W("gsc-cursor-box");g=this.sg(a);c[v](g);T(a.G,c)}if(e){q(a.vb,"("+a.h.results[E]+")");a.w.da==google[J].b.La||a.w.da==google[J].b.Sa?this.Qa(a,b):this.Qa(a,h);(c=a.h.Re())&&T(a.W,c)}else{q(a.vb,"(0)");q(a.W,"");this.Qa(a,h)}a.w.da=a.w.bf;this.Fb&&this.Fb(this,a.h);if(this.rb&&l&&!this.ye&&j.facets){a=this[w][A];j=j.facets;for(c=0;c<j[E];c++){l=j[c];
e=new google[J].g;if(r){r.m&&e.Ba(r.m,l.label);if(r.B)e.B=r.B;if(r.Pi)e.Aa=r.Aa}e.Lb(l.anchor);this.Va(e);e.Y(r.za);this.S!=google[J].b.ra&&e[M](a)}if(this.e[E]>1&&!this.ye)t(this.ha,"gsc-tabsArea");for(c=0;c<this.e[E];c++)if(!this.l[c]){this.Ne(c);this.Me(c);Z(this.l[c].$,"gsc-tabHeader");Z(this.l[c].J,"gsc-tabData");Z(this.l[c].$,"gsc-tabhInactive");Z(this.l[c].J,"gsc-tabdInactive")}this.ye=b}}};P(google[J].b[F],"onSearchComplete",google[J].b[F].aa);
google[J].b[F].sg=function(a){for(var c=W("gsc-cursor"),d=a.h[H],e=0;e<d.pages[E];e++){var g="gsc-cursor-page";if(e==d.currentPageIndex)g+=" gsc-cursor-current-page";g=U(d.pages[e].label,g);ma(g,S(this,google[J].b[F].hh,[a,e]));c[v](g)}return c};
google[J].b.he={border:"border",borderColor:"border-color",borderStyle:"border-style",borderWidth:"border-width",borderTop:"border-top",borderTopColor:"border-top-color",borderTopStyle:"border-top-style",borderTopWidth:"border-top-width",borderRight:"border-right",borderRightColor:"border-right-color",borderRightStyle:"border-right-style",borderRightWidth:"border-right-width",borderBottom:"border-bottom",borderBottomColor:"border-bottom-color",borderBottomStyle:"border-bottom-style",borderBottomWidth:"border-bottom-width",
borderLeft:"border-left",borderLeftColor:"border-left-color",borderLeftStyle:"border-left-style",borderLeftWidth:"border-left-width",color:"color",cssFloat:"float",styleFloat:"float",clear:"clear",cursor:"cursor",display:"display",font:"font",fontFamily:"font-family",fontSize:"font-size",fontStyle:"font-style",fontWeight:"font-weight",height:"height",margin:"margin",marginTop:"margin-top",marginRight:"margin-right",marginBottom:"margin-bottom",marginLeft:"margin-left",overflow:"overflow",padding:"padding",
paddingTop:"padding-top",paddingRight:"padding-right",paddingBottom:"padding-bottom",paddingLeft:"padding-left",textAlign:"text-align",textDecoration:"text-decoration",textTransform:"text-transform",verticalAlign:"vertical-align",visibility:"visibility",width:"width"};
google[J].b.Ve=function(a,c){if(ab("safari")||ab("konqueror"))alert("google.search.SearchControl.inlineCurrentStyle is not supported on Safari");else{var d=b;if(c)d=c;if(d)for(d=0;d<a.childNodes[E];d++)google[J].b.Ve(a.childNodes[d],b);if(a.nodeType==1){var e,g,j=h;d=h;if(m[Ma]){e=m[Ma](a,f);j=g=b}else if(a[Qa]){e=a[Qa];g=h;j=b}if(j){for(var l in e)if(google[J].b.he[l]){j=google[J].b.he[l];var r=e[l];if(l=="display"&&r=="none"){q(a,"");d=b}if(e[l]!="")g?a[I].setProperty(j,r):a[I][za](j,r)}if(d)if(!g)a.outerHTML=
'<div style="display:none"/>'}}}};P(google[J].b,"inlineCurrentStyle",google[J].b.Ve);google[J].b[F].Dg=function(a){a=a?a:this.k;var c=f;if(m[Ma])c=m[Ma](a,f);else if(a[Qa])c=a[Qa];else if(o.defaultView[Ma])c=o.defaultView[Ma](a,f);return c?ca(c[x],10):300};google[J].b[F].Jb=function(a,c){this.Fb=eb(a,c)};P(google[J].b[F],"setSearchCompleteCallback",google[J].b[F].Jb);google[J].b[F].Ah=function(a,c){this.Zc=eb(a,c)};P(google[J].b[F],"setSearchStartingCallback",google[J].b[F].Ah);
google[J].b[F].Uc=function(a,c){a.ad(c);var d=h;switch(c){default:case google[J].C.qc:if(a.G)na(a.G[I],"none");break;case google[J].C.pc:if(a.G)na(a.G[I],"block");if(a.h.za!=google[J].a.ia)d=b;a.h.Y(google[J].a.ia);break;case google[J].C.ie:if(a.G)na(a.G[I],"block");if(a.h.za!=google[J].a.ta)d=b;a.h.Y(google[J].a.ta)}if(d){d=this[w][A];if(d[E]){this.nb=h;t(this.Ia,"gsc-resultsbox-visible");this.Sb();if(!a.yb){$(a.k,"gsc-resultsbox-invisible");Z(a.k,"gsc-resultsbox-visible")}a.w.da=google[J].b.Sa;
a.h[M](d)}}};google[J].b[F].hh=function(a,c){this.nb=h;t(this.Ia,"gsc-resultsbox-visible");this.Sb();if(!a.yb){$(a.k,"gsc-resultsbox-invisible");Z(a.k,"gsc-resultsbox-visible")}a.w.da=google[J].b.Sa;a.h.Te(c)};
google[J].Q=function(a,c,d){var e=qb("gsc-search-box");e.acceptCharset="utf-8";var g=f,j=Q["search-uc"],l=Q[J];if(d){if(d.buttonText)l=j=d.buttonText;if(d.clickableBrandingUrl){g="http://www.google.com";if(typeof d.clickableBrandingUrl=="string"&&d.clickableBrandingUrl[C](/^http:\/\/[a-z]*\.google\.com/))g=d.clickableBrandingUrl;g=pb(g,f,"_BLANK");t(g,"gsc-branding-clickable")}}this.$b=rb(j,"gsc-search-button");s(this.$b,l);if(a){d="gsc-branding-img";this.yc=U(Q.blank,"gsc-clear-button");s(this.yc,
Q["clear-results"])}else d="gsc-branding-img-noclear";ga(this,sb(f,"gsc-input",f));this[w].name="search";s(this[w],l);l=lb(f,f,"gsc-search-box");T(e,l);l=mb(l,0);this.We=X(l,"gsc-input");j=X(l,"gsc-search-button");if(a){a=X(l,"gsc-clear-button");T(a,this.yc)}T(this.We,this[w]);T(j,this.$b);a=lb(f,f,"gsc-branding");T(e,a);l=mb(a,0);this.userDefinedCell=X(l,"gsc-branding-user-defined");a=X(l,"gsc-branding-text");l=X(l,d);j=U(Q["powered-by"],"gsc-branding-text");var r=google[L][Ca]+"/css/small-logo.png";
d=d;if(ab("msie")){d=W(d);d[I].filter='progid:DXImageTransform.Microsoft.AlphaImageLoader(src="'+r+'")';ha(d[I],"51px");pa(d[I],"15px")}else d=ob(r,f,f,d);d=d;T(a,j);if(g){T(g,d);T(l,g)}else T(l,d);this.gf=e;fb(c);T(c,this.gf)};O("google.search.SearchForm",google[J].Q);google[J].Q[F].nf=function(a,c){this.rf=S(this,this.Hh,[this]);this.dc=S(a,c,[this]);this.gf.onsubmit=this.rf;ma(this.$b,this.rf)};P(google[J].Q[F],"setOnSubmitCallback",google[J].Q[F].nf);
google[J].Q[F].mf=function(a,c){ma(this.yc,S(a,c,[this]))};P(google[J].Q[F],"setOnClearCallback",google[J].Q[F].mf);google[J].Q[F].Hh=function(){var a=this.We[wa],c=this[w][A];this.dc&&this.dc();if(ab("msie")){var d=this,e;e=c[E]*8>=a?a-6:"99%";m[Ia](function(){ha(d[w][I],e)},1)}return h};oa(google[J].Q[F],function(a){if(a)ia(this[w],a);this.dc&&this.dc()});P(google[J].Q[F],"execute",google[J].Q[F][M]);
google[J].Q[F].Mg=function(){var a=this[w],c=function(){if(a[A]=="")a[I].background="#FFFFFF url(http://www.google.com/coop/intl/"+google[J][Ua]+"/images/google_custom_search_watermark.gif) left no-repeat"};a.onblur=c;a.onfocus=function(){a[I].background="#FFFFFF"};c()};google[J].i=function(a,c){google[J].b[K](this);this.rb=b;this.Y(google[J].a.ta);var d={iframes:b};d.adtest=c&&c.adtest||f;this.qb("",d);this.cf=h;this.ob=new google[J].g;this.Je=typeof a=="string"?a:f;if(a==n){a={crefUrl:"http://www.google.com/coop/tools/autocse?referer="+m[La]};this.Oh=b}this.ob.Ba(a);this.ob.ec=Q.cse;c&&c[google[J].a.Ua]&&this.ob.X(google[J].a.Ua,c[google[J].a.Ua]);this.Va(this.ob);this.Ib(google[J].b.Td);this.Lh=(new Date)[Da]()};O("google.search.CustomSearchControl",google[J].i);
Za(google[J].i,google[J].b);google[J].d=function(a,c,d){this.Gb=a;this.ug=d;this.Pa=c[A];this.tf=this.sf=0;this.Cb=h;this.eh="";this.Bb={};this.Pb=google[J].d.Bf+p[ua](p.random()*2E4)+google[J].d.Ke;google[J].d.Ke++;var e=this;google[J].i[this.Pb]=function(g){e.gh(g)};this.oa=c.id;if(!this.oa){this.oa="q"+this.Pb;c.id=this.oa}this.Ac="c"+this.Pb};google[J].d.Bf="GcrcGcsc";google[J].d.Ke=0;google[J].d.Kd=0;google[J].d.Qb=google[J].d.Kd;google[J].d.Ld=2;google[J].d.Rf=10;google[J].d.zf=10;
google[J].d.Af=1;google[J].d.zc=google[J].d.Ld;google[J].d.$f=5E3;google[J].d.le=500;google[J].d.Zf=300;google[J].d.zd=25;google[J].d.Ya=google[J].d.zd;google[J].d.Qf=300;google[J].d.Wd=25;google[J].d.Df=2E3;google[J].d.jb=40;google[J].d.sc=38;google[J].d.Ef=13;google[J].d.Ff=27;google[J].d.cg=32;google[J].d.yf=8;google[J].d.Yf=45;
google[J].d.$g=function(a,c){var d=0;if(m&&m[Ya]&&m[Ya].keyCode)d=m[Ya].keyCode;else if(c&&c.which)d=c.which;if(!a.Cb&&d!=google[J].d.jb)return b;var e=o[z](a.oa);if(d==google[J].d.Ef){a.qf();return h}else if(d==google[J].d.sc){a.$e(d);return h}else if(d==google[J].d.jb){a.$e(d);return h}else if(d==google[J].d.Ff){var g=(new Date)[Da]();a.Yb();ia(e,a.Pa);if(g<a.sf+google[J].d.Df)a.Cb=h;a.sf=g}if(a.Pa==e[A]||d<=google[J].d.Yf&&d!=google[J].d.cg&&d!=google[J].d.yf)return b;a.Wc()};
google[J].d.Vg=function(a){m[Ia](function(){a.Yb()},google[J].d.Zf)};N=google[J].d[F];N.rh=function(){var a=o[z](this.oa);if(a){a.onkeyup=this.Ge(google[J].d.$g,a.onkeyup);a.onblur=this.Ge(google[J].d.Vg,a.onblur)}};N.qf=function(){var a=o[z](this.oa);if(a){this.Pa=a[A];this.Yb();if(typeof this.Gb=="string")o[z](this.Gb)[sa]();else this.Gb[M]?this.Gb[M]():this.Gb[sa]()}};
N.$e=function(a){var c=o[z](google[J].i.nc);if(c){google[J].d.ed(c,this);var d=f;if(a==google[J].d.sc)d=c[Ta].previousSibling;else if(a==google[J].d.jb)d=c[Ta].nextSibling;d&&google[J].d.cc(d[ya],this)}else if((c=o[z](this.Ac))&&a==google[J].d.sc)google[J].d.cc(c[ya].lastChild[ya],this);else if(c&&a==google[J].d.jb)google[J].d.cc(c[ya][ya][ya],this);else if(a==google[J].d.jb){this.Cb=b;this.Wc()}};N.Yb=function(){var a=o[z](this.Ac);a&&a[Ta][Pa](a)};
N.Wc=function(){var a=this,c=o[z](a.oa);a.Pa=c[A];if(a.Cb)a.tf+google[J].d.Ya>(new Date)[Da]()?m[Ia](function(){a.Wc()},google[J].d.Ya):m[Ia](function(){var d=o[D]("script"),e=(new Date)[Da]();d.src=["http://www.google.com/complete/search?q=",escape(c[A]),"&client=partner&source=gcsc&partnerid=",escape(a.ug),"&callback=",escape("google.search.CustomSearchControl."+a.Pb),"&ds=cse"][Wa]("");a.eh=c[A];o[Oa][v](d);a.Bb[c[A]]=e;a.tf=e;m[Ia](function(){a.uf(c[A])},google[J].d.le)},google[J].d.Qb+p[ua](p.random()*
google[J].d.zc))};
N.gh=function(a){var c=this,d=a[0];delete c.Bb[d];google[J].d.Qb=google[J].d.Kd;google[J].d.zc=google[J].d.Ld;if(google[J].d.Ya>google[J].d.zd)google[J].d.Ya-=google[J].d.Wd;var e=o[z](c.oa);if(d==e[A]){c.Yb();var g=a[1][E];if(!(g<1)){d=o[D]("tbody");for(var j=f,l=f,r=0;r<g;++r){l=o[D]("tr");j=o[D]("td");q(j,a[1][r][0]);var u=j.innerHTML.slice(0,a[0][E]),B=j.innerHTML.slice(a[0][E]);q(j,u+"<strong>"+B+"</strong>");j.onmouseover=c.Pe(j,google[J].d.cc);j.onmouseout=c.Pe(j,google[J].d.ed);ma(j,function(){c.qf()});
l[v](j);d[v](l)}a=o[D]("table");a.id=c.Ac;a[v](d);t(a,google[J].i.Cf);a[I].top=google[J].d.Fg(e)+Eb(e,b)+"px";a[I].left=google[J].d.Eg(e)+"px";o[Oa][v](a);ha(a[I],e[wa]+"px")}}};N.Pe=function(a,c){var d=this;return function(){c(a,d)}};N.Ge=function(a,c){var d=this;return function(e){a(d,e);c&&c(e)}};google[J].d.cc=function(a,c){var d=o[z](google[J].i.nc),e=o[z](c.oa);d&&google[J].d.ed(d,c);d=a.textContent;if(d==n)d=a.innerText;t(a,google[J].i.ag);a.id=google[J].i.nc;c.Pa=e[A];ia(e,d)};
google[J].d.ed=function(a,c){var d=o[z](c.oa);t(a,"");a.id="";ia(d,c.Pa?c.Pa:"")};google[J].d.Fg=function(a){var c=0;if(a[Ka]){for(;a[Ka];){c+=a.offsetTop-a.scrollTop;a=a[Ka]}c+=a.offsetTop}else if(a.y)c+=a.y;return c};google[J].d.Eg=function(a){var c=0;if(a[Ka]){for(;a[Ka];){c+=a.offsetLeft-a.scrollLeft;a=a[Ka]}c+=a.offsetLeft}else if(a.x)c+=a.x;return c};
google[J].d[F].uf=function(a){var c=this;if(c.Bb[a])if((new Date)[Da]()-c.Bb[a]>google[J].d.$f){google[J].d.Qb+=google[J].d.Af;google[J].d.Qb*=google[J].d.zf;google[J].d.zc+=google[J].d.Rf;if(google[J].d.Ya<google[J].d.Qf)google[J].d.Ya+=google[J].d.Wd;delete c.Bb[a]}else m[Ia](function(){c.uf(a)},google[J].d.le)};google[J].i.Ee=function(a,c,d){a=new google[J].d(d,c,a);a.Cb=b;a.rh()};P(google[J].i,"attachAutoCompletion",google[J].i.Ee);
google[J].i[F].Oe=function(){if(this.Je){google[J].i.Ee(this.Je,this[w],this);this.cf=b}else this.cf=h};P(google[J].i[F],"enableAutoCompletion",google[J].i[F].Oe);google[J].i[F].Tb=function(a,c){var d=c;d||(d=new google[J].M);d.kf(google[J].b.ra);if(this.Oh&&this.e[E]==1)this.Ih=b;google[J].b[F].Tb[K](this,a,d);t(this.k,"gsc-control-cse");d.Fe&&this.Oe()};P(google[J].i[F],"draw",google[J].i[F].Tb);
oa(google[J].i[F],function(a){var c=this.k[wa];$(this.ba,"gsc-thinWrapper");if(c<google[J].i.Sf)this.Ea=h;else if(c<google[J].i.Uf)this.qb(this.Ma,{useNarrowTopAd:b,includeVerticalAds:h});else{c={useNarrowTopAd:h,includeVerticalAds:c>google[J].i.Tf};if(this.Ze)c.numTopAds=google[J].i.Vf;this.qb(this.Ma,c)}if((new Date)[Da]()-this.Lh<google[J].i.wf&&this.Ea){c=fa(m[La].href)[y](/\+/g," ");var d=fa(a)[y](/\+/g," ");this.Ea=c.indexOf(d)!=-1}google[J].b[F][M][K](this,a)});P(google[J].i[F],"execute",google[J].i[F][M]);
google[J].i[F].Lb=function(a){this.ob.Lb(a)};P(google[J].i[F],"setUserDefinedLabel",google[J].i[F].Lb);google[J].i[F].Va=function(a,c){google[J].b[F].Va[K](this,a,c);a.bc="gcsc"};P(google[J].i[F],"addSearcher",google[J].i[F].Va);google[J].i[F].vg=function(){google[J].b[F].qb("",{numTopAds:0,numSideAds:0});this.Ma=f;this.hf=h};P(google[J].i[F],"disableAds",google[J].i[F].vg);google[J].i[F].uh=function(){this.Ze=b};P(google[J].i[F],"setMoreAds",google[J].i[F].uh);google[J].i.xf="";
P(google[J].i,"AUTO_PUBID",google[J].i.xf);google[J].i.Sf=250;google[J].i.Uf=500;google[J].i.Tf=800;google[J].i.wf=500;google[J].i[F].Ze=h;google[J].i.Vf=4;google[J].i.nc="csc-completion-selected";google[J].i.ag="gsc-completion-selected";google[J].i.Cf="gsc-completion-container";google[J].t=function(){google[J].a[K](this);this.A="video";this.Ja="/GvideoSearch";this.wa="http://video.google.com/videosearch";this.U=h;this.$a=b;this.la=eb(this,this.xa);this.Za="gsc-videoConfig";this.q=f};O("google.search.VideoSearch",google[J].t);Za(google[J].t,google[J].a);google[J].t.H="GvideoSearch";P(google[J].t,"RESULT_CLASS",google[J].t.H);google[J].t.p=[];google[J].t.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].t.p[j];google[J].t.p[j]=f;a.aa(c,d,e,g)};
P(google[J].t,"RawCompletion",google[J].t.N);google[J].t[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].t.p,this):d;c=this.Ha(c==f?"google.search.VideoSearch.RawCompletion":c,d,e);if(a){a=a;if(this.L)a=a+" "+this.L;a="&q="+i(a);if(this.U)a+="&scoring=d";c+=a;this.z=a;if(e&&e!=0)this.z=this.z+"&start="+e}return c};
google[J].t[F].I=function(a){a.html&&delete a.html;var c=W(this.va());Z(c,"gs-result");var d=W("gs-image-box"),e=W("gs-text-box"),g=lb(),j=mb(g,0),l=X(j,"gs-image-box");j=X(j,"gs-text-box");T(l,d);T(j,e);T(c,g);g=google[J].a.gb(a.tbWidth,a.tbHeight,this.T);g=ob(a.tbUrl,g[x],g[Va],"gs-image");l=pb(a.url,f,this.v(),"gs-image");t(l,"gs-image");T(l,g);T(d,l);d=Y(a.url,a[Ea],this.v(),"gs-title");T(e,d);d=U(a[va],"gs-snippet");if(ab("msie"))pa(d[I],"2.6em");T(e,d);d=U(this.bb(new Date(a.published)),"gs-publishedDate");
T(e,d);d=Y("http://"+a.publisher,a.publisher,this.v(),"gs-publisher");T(e,d);a.html=c;this.Da(a.html)};P(google[J].t[F],"createResultHtml",google[J].t[F].I);
google[J].t.tg=function(a,c){var d=f;if(a.playUrl&&a.playUrl!=""){d=a.playUrl;var e="gsc-video-player";if(c)e=c;if(ab("opera")){var g=o[D]("object");t(g,e);g[za]("type","application/x-shockwave-flash");g[za]("data",d)}else{g=o[D]("embed");t(g,e);g[za]("type","application/x-shockwave-flash");g[za]("src",d);if(a.videoType)a.videoType=="Google"?g[za]("bgcolor","#000000"):g[za]("wmode","transparent");else g[za]("bgcolor","#000000")}d=W(c);d[v](g)}return d};P(google[J].t,"createPlayer",google[J].t.tg);
google[J].t[F].P=function(a){this.U=a==google[J].a.ua?b:h};P(google[J].t[F],"setResultOrder",google[J].t[F].P);google[J].t[F].xa=function(a,c){if(c){if(this.q==f){var d=W("gsc-configSetting");this.q=tb(f,"0",this.U,"gsc-configSettingCheckbox");T(d,this.q);T(d,U(Q["sort-by-date"],"gsc-configSettingCheckboxLabel"));var e=W("gsc-configSettingSubmit");T(e,rb(Q[Na],"gsc-configSettingSubmit"));T(d,e);T(a,d)}else ka(this.q,this.U);this.q[xa]()}else if(this.q)this.q[Ha]?this.P(google[J].a.ua):this.P(google[J].a.lb)};google[J].g=function(){google[J].a[K](this);this.A="web";this.Ja="/GwebSearch";this.wa="http://www.google.com/search";this.m=f;this.F=google[J].g.Z;this.B=this.Aa=this.Ga=this.Fc=this.Na=f};O("google.search.WebSearch",google[J].g);Za(google[J].g,google[J].a);google[J].g.H="GwebSearch";P(google[J].g,"RESULT_CLASS",google[J].g.H);google[J].g.pb="cx";P(google[J].g,"cxRestriction_CX",google[J].g.pb);google[J].g.Rb="cref";P(google[J].g,"cxRestriction_CREF",google[J].g.Rb);google[J].g.Z="none";
P(google[J].g,"cxRestriction_NONE",google[J].g.Z);google[J].g.p=[];google[J].g.N=function(a,c,d,e,g){var j=0;if(a)j=ca(a,10);a=google[J].g.p[j];google[J].g.p[j]=f;a.aa(c,d,e,g)};P(google[J].g,"RawCompletion",google[J].g.N);google[J].g[F].Nh=function(a){return a[y](/\s+$/,"")[y](/^\s+/,"")};google[J].g[F].Tg=function(a){a=this.Nh(a);return a[y](/\s+/g,"_")[Xa]()};
google[J].g[F].ma=function(a,c,d,e){d=d==f?google[J].a.qa(google[J].g.p,this):d;if(this.F==google[J].g.Z&&this.Ni==google[J].a.Ta)throw createException("The resultset size google.search.Search.FILTERED_CSE_RESULTSET can  only be used for querying filtered Custom Search Engines.");c=this.Ha(c==f?"google.search.WebSearch.RawCompletion":c,d,e);if(a){a=a;if(this.L)a=a+" "+this.L;if(this.m&&this.F!=google[J].g.Z&&this.Fc){d=this.Fc;var g=a;if(this.Na!=f)g=a+" more:"+this.Na;d=d[y](/__HL__/,google[J][Ua]);
this.Ga=d=d[y](/__QUERY__/,i(g))}if(this.m&&this.F==google[J].g.Z)a=a+" site:"+this.m;d="";if(this.m&&this.F!=google[J].g.Z){if(this.F==google[J].g.pb)d=d+"&cx="+this.m;else if(this.F==google[J].g.Rb)d=d+"&cref="+i(this.m);if(this.Na!=f)a=a+" more:"+this.Na}d=d+"&q="+i(a);if(this.Aa)d=d+"&safe="+this.Aa;if(this.B)d+=this.B;c+=d;this.z=d;if(e&&e!=0)this.z=this.z+"&start="+e}if(m.google[L].GoogleLocale)c+="&gl="+i(m.google[L].GoogleLocale);return c};
google[J].g[F].Le=function(a){a.html&&delete a.html;var c=W("gs-promotion");Z(c,"gs-result");var d;d=a.url;var e=a[Ea],g=this.v(),j=U(f,"gs-title"),l=o[D]("a");l.href=d;e&&T(l,hb(e));t(l,"gs-title");if(g)la(l,g);j[v](l);d=j;T(c,d);d=lb(0,0);e=mb(d,0);T(c,d);if(a.image){d=a.image;d=ob(d.url,d[x],d[Va],"gs-promotion-image");g=nb("gs-promotion-image-td");T(g,d);T(e,g)}if(a.bodyLines){g=nb();var r=W();T(e,g);T(g,r);e=a.bodyLines;for(g=0;g<e[E];g++){d=e[g];j=d[Ea];l=d.url;var u=d.visibleUrl;d=W("gs-snippet");
if(l&&u){l=pb(l,u,this.v(),"gs-title");T(d,l)}j&&T(d,hb(j));T(r,d)}}d=ib(a.visibleUrl,"gs-visibleUrl");T(r,d);Z(d,"gs-visibleUrl-short");a.html=c};P(google[J].g[F],"createPromotionHtml",google[J].g[F].Le);google[J].g[F].I=function(a){a.html&&delete a.html;la(a,this.v()||n);a.html=google[J].r.Zb("webResult",a);this.Da(a.html)};P(google[J].g[F],"createResultHtml",google[J].g[F].I);
google[J].g[F].Ba=function(a,c,d){this.sb=this.Ga=f;var e=h;if(a==f||typeof a=="string"&&a==""){e=h;this.m=f;this.F=google[J].g.Z;this.sb=this.Na=f}else if(typeof a=="string")if(e=a[C](/(^partner-pub-\d*:.*)|(^\d{21}:.*)/)){this.m=a;this.F=google[J].g.pb}else{this.m=a;this.F=google[J].g.Z}else if(a.siteUrl){e=h;this.m=a.siteUrl}else if(a.cseId){e=b;this.m=a.cseId;this.F=google[J].g.pb}else if(a.crefUrl){e=b;this.m=a.crefUrl;this.F=google[J].g.Rb;this.sb=Q["linked-cse-error-results"]}else{e=h;this.m=
f;this.F=google[J].g.Z;this.Na=f}if(e){if(c)this.Na=this.Tg(c);if(d)if(d[C](/__HL__/)&&d[C](/__QUERY__/))this.Fc=d;if(this.F==google[J].g.Rb)if(!this.m[C](/^http:\/\/www\.google\.com\/coop\/tools\/autocse\?referer=/))(new Image).src="http://www.google.com/cse/tools/ping?cref="+i(this.m)+"&nocache="+Number(new Date)}};P(google[J].g[F],"setSiteRestriction",google[J].g[F].Ba);
google[J].g[F].X=function(a,c){if(a==google[J].a.kc)this.Aa=c?c==google[J].a.mc||c==google[J].a.lc||c==google[J].a.ge?c:f:f;if(a==google[J].a.Ua)if(c)for(var d in c){var e=c[d];if(d=="lr"||d=="usg"||d=="filter"||d=="gl"||d=="richsnippet"||d=="sort"){if(this.B==f)this.B="&";else this.B+="&";this.B+=d+"="+i(e)}}else this.B=f};P(google[J].g[F],"setRestriction",google[J].g[F].X);google[J].g[F].Y=function(a){if(google[J].a.Ta==a)this.za=google[J].a.Ta;else google[J].a[F].Y[K](this,a)};
P(google[J].g[F],"setResultSetSize",google[J].g[F].Y);if(!google[J].NoOldNames){k("GwebSearch",google[J].g);k("GbookSearch",google[J].n);k("GblogSearch",google[J].s);k("GvideoSearch",google[J].t);k("GnewsSearch",google[J].o);k("GlocalSearch",google[J].f);k("GimageSearch",google[J].c);k("GpatentSearch",google[J].j);k("GSearch",google[J].a);k("GSearchControl",google[J].b);k("GSearchForm",google[J].Q);k("GsearcherOptions",google[J].D);k("GdrawOptions",google[J].M)};google[J].r={};google[J].r.fg=function(a){google[J].r.Xb.unshift(a);return google[J].r.Xb};O("google.search.Csedr.addOverride",google[J].r.fg);google[J].r.Xb=["base_",""];google[J].r.yg=function(a,c){google[J].r.Lc[a]||(google[J].r.Lc[a]=eval("[function(Vars,render,html){with(Vars)return("+a+")}][0]"));return google[J].r.Lc[a](c,google[J].r.Zb,google[J].r.xb)};google[J].r.Lc={};google[J].r.xb=function(a){var c=o.createDocumentFragment(),d=o[D]("div");for(q(d,a);d[ya];)c[v](d[ya]);return c};
google[J].r.Zb=function(a){if(google[J].r.bd){o[Oa][v](google[J].r.xb(google[J].r.bd));google[J].r.bd=0}for(var c=0;!a[v];){if(c>=google[J].r.Xb[E])return google[J].r.xb(a+" not found");a=o[z](google[J].r.Xb[c++]+a)||a}for(var d={},e=1;e<arguments[E];e++)for(c in arguments[e])d[c]=arguments[e][c];try{var g=google[J].r.xb(""),j,l;e=0;for(var r,u,B=function(jb){jb="data-"+jb;u=(r=G.getAttribute(jb))?google[J].r.yg(r,d):"";j.removeAttribute&&j.removeAttribute(jb);return r},G=a[ya];G;G=l?G:G.nextSibling){j=
G[Aa](h);if(G.nodeType!=1){if(G.nodeType!=3||G.nodeValue[C](/\S/))g[v](j)}else{B("foreach");if(!l)if(r){d.Foreach=u&&typeof u[Wa]=="function"?u:[u];c=0;l=1}if(l)if(c<d.Foreach[E])d.Cur=d.Foreach[d.Index=c++];else{l=0;continue}if(B("if"))e=0;if(r||B("elif"))if(e||!u)continue;else e=1;if(!B("attr")||u){g[v](j);if(r)for(var V in u)if(u[V]!=n)if(V=="class")t(j,u[V]);else if(V=="style"&&ab("msie"))j[I].cssText=u[V];else j[za](V,u[V])}else j=g;var Cb=B("body")?u&&u[v]?u:o.createTextNode(u):google[J].r.Zb(G,
d,B("vars")?u:{});try{Cb&&j[v](Cb)}catch(Ob){}}}return g}catch(Mb){return google[J].r.xb(Mb.toString()+": "+r)}};O("google.search.Csedr.render",google[J].r.Zb);google[J].r.bd=' <div style="display:none"> <div id="base_webResult"> <div class="gs-webResult gs-result" data-vars="{longUrl:function() { var i = unescapedUrl.indexOf(visibleUrl); return i < 1 ? visibleUrl : unescapedUrl.substring(i);}}"> <div data-if="Vars.richSnippet" data-attr="0" data-body="render(\'thumbnail\',richSnippet,{url:unescapedUrl,target:target})"></div> <div class="gs-title"> <a class="gs-title" data-attr="{href:unescapedUrl,target:target}" data-body="html(title)"></a> </div> <div class="gs-snippet" data-body="html(content)"></div> <div class="gs-visibleUrl gs-visibleUrl-short" data-body="visibleUrl"></div> <div class="gs-visibleUrl gs-visibleUrl-long" data-body="longUrl()"></div> <div data-if="Vars.richSnippet && Vars.richSnippet.action" class="gs-actions" data-body="render(\'action\',richSnippet,{url:unescapedUrl,target:target})"></div> </div> </div> <div id="base_thumbnail"> <div data-attr="0" data-vars="{tn:Vars.thumbnail && thumbnail.src ? thumbnail : {src:Vars.document && document.thumbnailUrl}}"> <div data-if="tn.src" class="gs-image-box gs-web-image-box"> <a class="gs-image" data-attr="{href:url,target:target}"> <img class="gs-image" data-attr="{src:tn.src, width:tn.width || 100, height: tn.height}"/> </a> </div> </div> </div> <div id="base_action"> <div data-foreach="Vars.action" data-attr="0"> <div data-attr="{\'class\': \'gs-action \' + Cur[\'class\']}" data-if="Cur.url && Cur.label"> <a class="gs-action" data-attr="{href:Cur.url,target:target}" data-body="Cur.label"></a> </div> </div> </div> </div> ';
google.loader.loaded({"module":"search","version":"1.0","components":["default"]});
google.loader.eval.search = function() {eval(arguments[0]);};if (google.loader.eval.scripts && google.loader.eval.scripts['search']) {(function() {var scripts = google.loader.eval.scripts['search'];for (var i = 0; i < scripts.length; i++) {google.loader.eval.search(scripts[i]);}})();google.loader.eval.scripts['search'] = null;}})();