document.write("<"+"script>\n");
document.write("if (location){\n");
document.write("\tloc=location.href;\n");
document.write("\tpos=loc.indexOf('PublisherDashboard/Creative.aspx')\n");
document.write("\tif (pos!=-1)\n");
document.write("\t{\n");
document.write("\t\t//document.write('....');\n");
document.write("\t\tdocument.write('<"+"script src=\"http://img6.cdn.adjuggler.com/images/Client416746/1255728399476_em_300x250_view.js\">'+'<"+"/'+'script>');\n");
document.write("\n");
document.write("\t}\n");
document.write("\telse{\n");
document.write("\t\tvar _em_allow_invite=1;\n");
document.write("\t\tvar _em_width=300; \n");
document.write("\t\tvar _em_height=250; \n");
document.write("\t}\n");
document.write("}else{\n");
document.write("\t\tvar _em_allow_invite=1;\n");
document.write("\t\tvar _em_width=300; \n");
document.write("\t\tvar _em_height=250; \n");
document.write("\n");
document.write("}\n");
document.write("<"+"/script>");
document.write("<"+"script type=\"text/javascript\"> var NetworkID = 1; var AdSpotID = \"375493\"; <"+"/script> <"+"script type=\"text/javascript\" src=\"http://admax-cdn.effectivemeasure.net/emn.js\"><"+"/script> <"+"img src=\"http://ads.admaxasia.com/servlet/cookie?action=set&name=setsurvey&value=1&maxage=2592000\" width=\"1\" height=\"1\" style=\"position:absolute;\">");
